### PR TITLE
[#1910] fix: Remove the method name from the log

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

From the log4j document, we should not print out the method name into the log4j properties.

### Why are the changes needed?

Fix: #1910

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Needn't

### CODE REVIEW

**Comment by zuston** [comment]
@rickyma

**Comment by rickyma** [comment]
This is not from log4j2. I don't think log4j2 will hang.

**Comment by zuston** [comment]
> This is not from log4j2. I don't think log4j2 will hang.

Is this right? I'm not sure. Please see https://logging.apache.org/log4j/2.x/performance.html#asynchronous-logging-with-caller-location-information

**Comment by rickyma** [comment]
Your jstack log does tell it's from log4j2. Instead, it should belong to log4j1.

**Comment by rickyma** [comment]
We don't need the `slf4j-reload4j` dependency, we can remove it. That's probably the reason why it hangs.

**Comment by zuston** [comment]
Yes. I know this cause that not happen on the log4j2. But the doc indicates that we should not use the `Method` in the log style

**Comment by rickyma** [comment]
We can remove it. When debuging, we can add it back manually. 

Or we could just add something like a debug switch, then we can use different log4j2 configurations in different scenarios (test/prod).

**Comment by zuston** [comment]
> We can remove it. When debuging, we can add it back manually.
> 
> Or we could just add something like a debug switch, then we can use different log4j2 configurations in different scenarios (test/prod).

Ok for me. I just hope the example log4j xml could be stable and available

**Review by rickyma — APPROVED** [review]
LGTM

**Comment by rickyma** [comment]
You can modify the description of the issue https://github.com/apache/incubator-uniffle/issues/1910, because the jstack log has nothing to do with this PR. This PR will not solve the issue.

**Pull request merged**
