### PR TITLE
Set the default disk capacity to the total space

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Set the default disk capacity to the total space

### Why are the changes needed?
When shuffle-servers are colocated with NodeManagers, the disk capacity is hard to set. Because when it's equal with the total space, it will cause the most shuffle-servers startup fail due to free-space checking. If not, it will waste some disk resources.

And the default disk capacity is 1TB, it's not out-of-box value. So this PR is to set the default value of 'rss.server.disk.capacity' to the disk total space.

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by zuston** [comment]
This problem occurred in our internal uniffle cluster. PTAL @jerqi

**Comment by jerqi** [comment]
Should we modify the document at the same time?

**Comment by zuston** [comment]
> Should we modify the document at the same time?

Yes. If this direction is OK, I will go ahead to add more tests and doc.

**Comment by jerqi** [comment]
It's ok for me.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @zuston

**Comment by zuston** [comment]
Thanks @jerqi

**Pull request merged**
