### PR TITLE
[Improvement] Add the number of unhealthy nodes in CoordinatorMetrics

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

To solve #146 

### Why are the changes needed?

The number of unhealthy nodes can be viewed on the monitoring.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need.

### CODE REVIEW

**Comment by smallzhongfeng** [comment]
cc @jerqi

**Comment by jerqi** [comment]
Could you add some tests cases in `HealthCheckCoordinatorGrpcTest`?

**Comment by smallzhongfeng** [comment]
Could you tell me what needs to be tested. @jerqi Because the current modified method is `nodeCheck`, I think it is enough not to affect the original test results.WDYT?

**Review by jerqi — APPROVED** [review]
Thanks @smallzhongfeng ,LGTM

**Pull request merged**
