### PR TITLE
[#1330] improvement: optimize tips for checking replica settings

### PR DESCRIPTION
**Pull request by guixiaowen**
### What changes were proposed in this pull request?

The tips for checking replica settings is a bit unclear.

### Why are the changes needed?

This tip may be misleading

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need

### CODE REVIEW

**Comment by guixiaowen** [comment]
@xianjingfeng Could you help me review this pr?

**Review by xianjingfeng — APPROVED** [review]
LGTM

**Comment by xianjingfeng** [comment]
@guixiaowen There are some fails in CI, you can check them by the following commands.
```shell 
mvn -B -fae spotless:check -Pspark3
mvn -B -fae checkstyle:check -Pspark3
```

**Comment by guixiaowen** [comment]
> @guixiaowen There are some fails in CI, you can check them by the following commands.
> 
> ```shell
> mvn -B -fae spotless:check -Pspark3
> mvn -B -fae checkstyle:check -Pspark3
> ```

Ok, let me check it.

**Comment by guixiaowen** [comment]
> > @guixiaowen There are some fails in CI, you can check them by the following commands.
> > ```shell
> > mvn -B -fae spotless:check -Pspark3
> > mvn -B -fae checkstyle:check -Pspark3
> > ```
> 
> Ok, let me check it.

@xianjingfeng hi, I checked it carefully, there should be no problem.

**Review by xianjingfeng — APPROVED** [review]
LGTM. Thanks @guixiaowen

**Pull request merged**
