### PR TITLE
[#532] SpotBugs: Fix SC_START_IN_CTOR

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

Fix SC_START_IN_CTOR from SpotBugs suggestion.

### Why are the changes needed?

Fix SC_START_IN_CTOR from SpotBugs suggestion.

Fix: #532

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
unit test

### CODE REVIEW

**Comment by lifeSo** [comment]
Fix SC_START_IN_CTOR error from SpotBugs suggestion.

image

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by zuston — APPROVED** [review]
+1

**Comment by lifeSo** [comment]
https://github.com/apache/incubator-uniffle/issues/1439

**Pull request merged**
