### PR TITLE
[#2288] feat(dashboard): Show nodeInfo in excludeNode page

### PR DESCRIPTION
**Pull request by kuszz**
### What changes were proposed in this pull request?
Show nodeInfo in excludeNode page
image

企业微信截图_b08453cf-21af-43ed-bcdd-4238390c9823

### Why are the changes needed?
Fix: #2288 

### Does this PR introduce _any_ user-facing change?
No.

### CODE REVIEW

**Comment by jerqi** [comment]
@yl09099 Could you help review this pull request?

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by yl09099** [comment]
Why is your image above in the active option with add and delete buttons?

**Comment by kuszz** [comment]
> Why is your image above in the active option with add and delete buttons?

I have changed the image, the add and delete buttons only in exclude node page

**Comment by jerqi** [comment]
@yl09099 Do you have another suggestion?

**Comment by yl09099** [comment]
LGTM

**Comment by jerqi** [comment]
Merged. Thanks all.

**Pull request merged**
