### PR TITLE
[#1006] feat(spark): Support Spark 3.4

### PR DESCRIPTION
**Pull request by summaryzb**
### What changes were proposed in this pull request?
1. Add maven profile `spark3.4`
2. Enable tests for Spark 3.4 in CI 
3. Fix broken tests

### Why are the changes needed?
https://github.com/apache/incubator-uniffle/issues/1006

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass Test

### CODE REVIEW

**Comment by LuciferYang** [comment]
@summaryzb There are some tests related to Spark 3.4 that have failed. Could you fix them first.

https://github.com/apache/incubator-uniffle/actions/runs/5760857388/job/15617648318?pr=1082

On the other hand, I encountered an error when compiling locally. It seems we need to add a `numPartitions` method for `MockTaskContext`.

```
[ERROR] /Users/yangjie01/SourceCode/git/incubator-uniffle/integration-test/spark3/src/test/java/org/apache/uniffle/test/GetReaderTest.java:[199,17] 错误: MockTaskContext不是抽象的, 并且未覆盖TaskContext中的抽象方法numPartitions()
```

**Comment by LuciferYang** [comment]
@summaryzb One piece of information that may help fix the tests is that Spark 3.4 has started to use slf4j2, while slf4j 1.7.x was used before. Some code or dependency changes will be involved in the version migration, you can refer to https://github.com/apache/spark/pull/37844, hope this helps you.

**Comment by summaryzb** [comment]
> @summaryzb One piece of information that may help fix the tests is that Spark 3.4 has started to use slf4j2, while slf4j 1.7.x was used before. Some code or dependency changes will be involved in the version migration, you can refer to [apache/spark#37844](https://github.com/apache/spark/pull/37844), hope this helps you.

Fixed, log4j-core was specified a certain version while other log4j group use different versions

**Comment by summaryzb** [comment]
@LuciferYang PTAL

**Review by LuciferYang — APPROVED** [review]
+1, LGTM

**Review by jerqi — APPROVED** [review]
LGTM, thanks @LuciferYang @summaryzb 
@LuciferYang Could you merge this pr?

**Comment by LuciferYang** [comment]
Merged into master. Thanks @summaryzb and @jerqi ~

**Pull request merged**
