### PR TITLE
 [#1401] feat(dashboard): Add mock data to the Dashboard front end.

### PR DESCRIPTION
**Pull request by yl09099**
### What changes were proposed in this pull request?

When the Dashboard front-end development needs to show some effects, it is necessary to start the backend to provide the corresponding interface to see the effect. After the mock data is added, you can see the page effect by intercepting the network request and directly using the mock data of the front-end.

### Why are the changes needed?

Fix: #1401 

### Does this PR introduce _any_ user-facing change?

Yes.

### How was this patch tested?

Develop UT.

### CODE REVIEW

**Comment by yl09099** [comment]
@jerqi @xianjingfeng @rickyma @maobaolong PATL.

**Comment by yl09099** [comment]
I hope to prioritize the incorporation of this PR, so as to facilitate the development of front-end effects. @rickyma

**Comment by rickyma** [comment]
Let @maobaolong @xianjingfeng take a look first. 

If no more comments, I'll merge this tonight.

**Review by maobaolong — APPROVED** [review]
I'm fine with this PR. Dashboard is a great component of Uniffle, it let us insight running status of all other services, hope dashboard can be better and better.

**Review by rickyma — APPROVED** [review]
LGTM. Feel free to add any comments.

**Comment by rickyma** [comment]
Merged. Thanks @yl09099 @maobaolong

**Pull request merged**
