### PR TITLE
[MINOR] Migrate RankValue to the package of the common class

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

More standardized, and the class can be extended in the future.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need.

### CODE REVIEW

**Comment by smallzhongfeng** [comment]
Please cc, just a minor change. @jerqi

**Comment by jerqi** [comment]
Could you give me a concrete example? Why do we need this pr?

**Comment by smallzhongfeng** [comment]
Because this static class is currently in `LowestIOSampleCostSelectStorageStrategy`, but `AppBalanceSelectStorageStrategy` will also use it, and other selection strategy may use it later, it will be common to set it as a normal class. In addition, sorting is required when selecting the optimal storage path. Sorting depends on this object. If other storage needs to rely on this `RankValue`, and more comparative attributes need to be added, it will be clearer to define these attributes in a separate class. WDYT ? @jerqi

**Comment by jerqi** [comment]
Why do we migrate RankValue to the package of the common class if shuffle server and client won't use RankValue.

**Comment by smallzhongfeng** [comment]
I see what you mean, but I think it is necessary to set it as a separate class. Put it under the coordinator package ？

**Comment by jerqi** [comment]
> I see what you mean, but I think it is necessary to set it as a separate class. Put it under the coordinator package ？

Coordinator package is better.

**Comment by jerqi** [comment]
Will you continue this pr?

**Comment by smallzhongfeng** [comment]
> @smallzhongfeng Will you continue this pr?

Done, sorry to take so long.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @smallzhongfeng

**Pull request merged**
