### PR TITLE
[#1668] fix: Replace assertions with exception-throwing codes

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Replace assertions with exception-throwing codes to make them work in production.

### Why are the changes needed?

For: https://github.com/apache/incubator-uniffle/issues/1668.
This will make the exception checks work and make the code more reliable.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL. @zuston @jerqi

**Comment by rickyma** [comment]
ping @zuston @jerqi

**Comment by rickyma** [comment]
Gently ping @zuston @jerqi

**Comment by rickyma** [comment]
ping @zuston @jerqi ~~~

**Review by zuston — APPROVED** [review]
lgtm

**Pull request merged**
