### PR TITLE
[#1062] fix(tez): Fix to use TezIdHelper to getTaskAttemptId instead of default IdHelper.

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

Fix to use TezIdHelper to getTaskAttemptId instead of default IdHelper.

### Why are the changes needed?

Fix to use TezIdHelper to getTaskAttemptId instead of default IdHelper.

Fix: [#1062](https://github.com/apache/incubator-uniffle/issues/1062)

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by lifeSo** [comment]
When  there is no task fail and attempt, the default IdHelper code before will work ok, but if where is task fail and attempt, it will filter block id.

The filter code:

ShuffleReadClientImp.java
    List<Long> removeBlockIds = Lists.newArrayList();
    blockIdBitmap.forEach(
        bid -> {
          if (!taskIdBitmap.contains(idHelper.getTaskAttemptId(bid))) {
            removeBlockIds.add(bid);
          }
        });

    for (long rid : removeBlockIds) {
      blockIdBitmap.removeLong(rid);
    }

idHelper.getTaskAttemptId(bid) will return wrong task attemt id if there is task attempt and use default idHelper.

**Comment by jerqi** [comment]
Could we add a ut for this pr?

**Comment by zhengchenyu** [comment]
@lifeSo 
A great catch. For now, can not read the blocks which are generated by recompute tasks.

I does not review here carefully. There are little different with my initial version. I doubt that how to generate the block id.
https://github.com/apache/incubator-uniffle/blob/1e4804b944bd91887748fc0ad2771825752f3a28/client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java#L157  Here I don't know why we use nextSeqNo.

**Comment by zhengchenyu** [comment]
@lifeSo 
But I doubt that how to generate the block id.
> I does not review here carefully before. There are little different with my initial version.

https://github.com/apache/incubator-uniffle/blob/1e4804b944bd91887748fc0ad2771825752f3a28/client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java#L157  
Here I don't know why we use nextSeqNo.

**Review by zhengchenyu — APPROVED** [review]

**Comment by lifeSo** [comment]
> @lifeSo But I doubt that how to generate the block id.
> 
> > I does not review here carefully before. There are little different with my initial version.
> 
> https://github.com/apache/incubator-uniffle/blob/1e4804b944bd91887748fc0ad2771825752f3a28/client-tez/src/main/java/org/apache/tez/common/RssTezUtils.java#L157
> 
> 
> Here I don't know why we use nextSeqNo.

One Shuffle Write task may write multi  block, so this block is differ from blockId and each block is differ from nextSeqNo.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @lifeSo @zhengchenyu . Merge this pr first.

**Comment by lifeSo** [comment]
> 

Thanks. Find ways to contribute more to the community.

**Pull request merged**
