### PR TITLE
[#1675][FOLLOWUP] fix(test): Fix flaky tests which may cause port conflicts

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Fix some flaky tests which may cause port conflicts sometimes.

### Why are the changes needed?

Fix: https://github.com/apache/incubator-uniffle/issues/1675.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unnecessary.

### CODE REVIEW

**Comment by rickyma** [comment]
This could be merged. Minor fixes. More stable for the test. It forgot to stop the server, which might cause port conflicts. @zuston @jerqi

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
LGTM. Please update the PR title to describe what's this PR changed rather than coarse grained desp.

**Comment by jerqi** [comment]
Maybe we should commit this to branch 0.9, too.

**Comment by zuston** [comment]
> Maybe we should commit this to branch 0.9, too.

Done

**Pull request merged**
