### PR TITLE
[#1405] improvement: modify instanceId in Prometheus to hostname

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

modify instanceId in Prometheus to hostname

### Why are the changes needed?

modify instanceId in Prometheus to hostname for better convenience

Fix:  https://github.com/apache/incubator-uniffle/issues/1405

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

unit test and prd test.

### CODE REVIEW

**Comment by lifeSo** [comment]
After apply the patch, we could see hostname from monitor instead of meanless id.
eg:
image

**Review by zuston — COMMENTED** [review]
I don't think this is a good direction. If I remembered correctly, users may deploy multiple servers on one machine @xianjingfeng Right?

**Comment by lifeSo** [comment]
> I don't think this is a good direction. If I remembered correctly, users may deploy multiple servers on one machine @xianjingfeng Right?

It is reasonable, but in our PRD, only one server in one matchine.

**Comment by zuston** [comment]
> > I don't think this is a good direction. If I remembered correctly, users may deploy multiple servers on one machine @xianjingfeng Right?
> 
> You are right, but in our PRD, only one server in one matchine.

So from my side, this PR is not general.

**Comment by xianjingfeng** [comment]
> > > I don't think this is a good direction. If I remembered correctly, users may deploy multiple servers on one machine @xianjingfeng Right?
> > 
> > You are right, but in our PRD, only one server in one matchine.
> 
> So from my side, this PR is not general.

+1

**Pull request closed without merging**
