### PR TITLE
[ISSUE-376] Fix concurrency problems may occur when the ApplicationManager register app

### LINKED ISSUE #376: [Bug] Concurrency problems may occur when the ApplicationManager registerApplicationInfo
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
appAndTime.remove(uuidFromApp);
appAndTime.put(appId, currentTimeMillis);
```
In the process of `registerApplicationInfo` in `ApplicationManager`, we need to remove the uuid and re insert it into the registered appId. This process is not atomic and may cause concurrency problems.
```
int currentAppNum = appAndTimes.size();
if (currentAppNum >= defaultAppNum) {
    ...
}
```
When `AccessQuotaChecker` getting `appAndTimes.size()`, it may be the number of apps before putting appId after removing uuid.

### Affects Version(s)

0.7.0

### Uniffle Server Log Output

[ERROR] 2022-11-29 17:57:39,386 Grpc-199 AccessAppQuotaChecker check - Denied by AccessAppQuotaChecker => User: xxxx, current app num is: 104, default app num is: 80. We will reject this app[uuid=468366284-108712]

### Uniffle Engine Log Output

_No response_

### Uniffle Server Configurations

_No response_

### Uniffle Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by smallzhongfeng**
### What changes were proposed in this pull request?

Lock when reading and writing the map `appAndTimes`.

### Why are the changes needed?

To resolve #376 .

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Passed origin uts.

### CODE REVIEW

**Comment by smallzhongfeng** [comment]
cc @jerqi @leixm

**Comment by leixm** [comment]
+1 LGTM.

**Comment by jerqi** [comment]
@leixm You could click the `approve`  button.

**Review by jerqi — APPROVED** [review]
Merged. thanks @leixm @smallzhongfeng

**Comment by smallzhongfeng** [comment]
Thanks all. @jerqi  @leixm

**Pull request merged**
