### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
Add issue template

### Why are the changes needed?
Provide some issue templates for users 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
No need.

### CODE REVIEW

**Comment by jerqi** [comment]
Our repo don't have `discussions`. Should we let users to discuss user questions with issues?

**Comment by jerryshao** [comment]
> Our repo don't have discussions tab. Should we let users to discuss user questions with issues?

This should be opened by repo maintainer (Apache Infra), I can create a request if we need this.

**Comment by jerryshao** [comment]
@jerqi can we please continue this PR, is there any further thing should be addressed in this PR?

**Review by jerryshao — APPROVED** [review]

**Comment by jerryshao** [comment]
close and reopen to trigger the UT again.

**Pull request merged**
