### PR TITLE
[MINOR] chore: Fix the issue of license loss

### PR DESCRIPTION
**Pull request by zhengchenyu**
### What changes were proposed in this pull request?

Fix the issue of license loss

### Why are the changes needed?

LICENSE file is missing but license directory which is from  grpc-netty-shaded-1.61.1.jar exists.

And when published maven artifacts, I can not close.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

test in dev and cluster

### CODE REVIEW

**Comment by zhengchenyu** [comment]
Before this PR, The files under META-INF are as follows:


```
xxuser@xxhost tmp % ll META-INF
total 96
drwxr-xr-x@ 15 zhengchenyu  staff    480 11  9 12:16 ./
drwxr-xr-x@ 10 zhengchenyu  staff    320 11 11 17:09 ../
-rw-r--r--@  1 zhengchenyu  staff  22734 11  9 12:16 DEPENDENCIES
-rw-r--r--@  1 zhengchenyu  staff    571 11  9 12:16 DISCLAIMER
-rw-r--r--@  1 zhengchenyu  staff    104 11  9 12:16 MANIFEST.MF
-rw-r--r--@  1 zhengchenyu  staff  11430 11  9 12:16 NOTICE
-rw-r--r--@  1 zhengchenyu  staff    439 10 10  2023 io.netty.versions.properties
drwxr-xr-x@  6 zhengchenyu  staff    192  5  5  2023 license/
drwxr-xr-x@ 15 zhengchenyu  staff    480 11  9 12:15 licenses/
drwxr-xr-x@ 11 zhengchenyu  staff    352 11  9 12:15 maven/
drwxr-xr-x@ 16 zhengchenyu  staff    512 11  9 12:16 native/
drwxr-xr-x@  4 zhengchenyu  staff    128  2  2  2024 native-image/
drwxr-xr-x@ 10 zhengchenyu  staff    320  2  1  1980 proguard/
drwxr-xr-x@ 10 zhengchenyu  staff    320 11  9 12:14 services/
drwxr-xr-x@  4 zhengchenyu  staff    128  1  6  2023 versions/
xx user@xx host tmp % ll META-INF/license
total 96
drwxr-xr-x@  6 zhengchenyu  staff    192  5  5  2023 ./
drwxr-xr-x@ 15 zhengchenyu  staff    480 11  9 12:16 ../
-rw-r--r--@  1 zhengchenyu  staff   6121  5  5  2023 LICENSE.aix-netbsd.txt
-rw-r--r--@  1 zhengchenyu  staff  12486  5  5  2023 LICENSE.boringssl.txt
-rw-r--r--@  1 zhengchenyu  staff  11358  5  5  2023 LICENSE.mvn-wrapper.txt
-rw-r--r--@  1 zhengchenyu  staff  11356  5  5  2023 LICENSE.tomcat-native.txt
```

I can not find LICENSE file in META-INF directory. But I found META-INF/license directory which is from `grpc-netty-shaded-1.61.1.jar.`

To be honest, I don't know whether these third-party library needs to be in directory META-INF/licenses, because these third-party are need by `grpc-netty-shaded-1.61.1.jar`. In this pr, these third-party library is ignored.

I guess that In some OS where files are not case sensitive. license directory conficts with License file. So License is missing.

**Comment by zhengchenyu** [comment]
After this PR, The files under META-INF are as follows:

```
xxxuser@xxxhost tmp % ll META-INF
total 128
drwxr-xr-x@ 15 zhengchenyu  staff    480 11 11 16:47 ./
drwxr-xr-x@ 10 zhengchenyu  staff    320 11 11 17:21 ../
-rw-r--r--@  1 zhengchenyu  staff  22734 11 11 16:47 DEPENDENCIES
-rw-r--r--@  1 zhengchenyu  staff    571 11 11 16:47 DISCLAIMER
-rw-r--r--@  1 zhengchenyu  staff  14157 11 11 16:47 LICENSE
-rw-r--r--@  1 zhengchenyu  staff    104 11 11 16:47 MANIFEST.MF
-rw-r--r--@  1 zhengchenyu  staff  11430 11 11 16:47 NOTICE
-rw-r--r--@  1 zhengchenyu  staff    439 10 10  2023 io.netty.versions.properties
drwxr-xr-x@ 15 zhengchenyu  staff    480 11 11 16:47 licenses/
drwxr-xr-x@ 11 zhengchenyu  staff    352 11 11 16:47 maven/
drwxr-xr-x@ 16 zhengchenyu  staff    512 11 11 16:47 native/
drwxr-xr-x@  4 zhengchenyu  staff    128  2  2  2024 native-image/
drwxr-xr-x@ 10 zhengchenyu  staff    320  2  1  1980 proguard/
drwxr-xr-x@ 10 zhengchenyu  staff    320 11 11 16:46 services/
drwxr-xr-x@  4 zhengchenyu  staff    128  1  6  2023 versions/

```

**Comment by jerqi** [comment]
Could you raise a pull request to the master branch?

**Comment by zhengchenyu** [comment]
> Could you raise a pull request to the master branch?

OK, raise pr to master after this pr is done!

To be honest, I'm not very familiar with licenses. Can you please review this? @jerqi @xianjingfeng

**Comment by jerqi** [comment]
Could you display the files in the `license` and `licenses`?

**Comment by zhengchenyu** [comment]
> Could you display the files in the `license` and `licenses`?

The files under META-INF/licenses are as follows:

```
drwxr-xr-x@ 15 zhengchenyu  staff    480 11 11 17:41 ./
drwxr-xr-x@ 15 zhengchenyu  staff    480 11 11 17:41 ../
-rw-r--r--@  1 zhengchenyu  staff   1075 11 11 17:41 LICENSE-animal-sniffer.txt
-rw-r--r--@  1 zhengchenyu  staff   1126 11 11 17:41 LICENSE-checker-qual.txt
-rw-r--r--@  1 zhengchenyu  staff  35082 11 11 17:41 LICENSE-hbase-shaded-jersey.txt
-rw-r--r--@  1 zhengchenyu  staff  35084 11 11 17:41 LICENSE-jakarta-annotation.txt
-rw-r--r--@  1 zhengchenyu  staff  35717 11 11 17:41 LICENSE-jakarta-inject.txt
-rw-r--r--@  1 zhengchenyu  staff  39394 11 11 17:41 LICENSE-javax-activation.txt
-rw-r--r--@  1 zhengchenyu  staff  36116 11 11 17:41 LICENSE-javax-annotation.txt
-rw-r--r--@  1 zhengchenyu  staff  36116 11 11 17:41 LICENSE-javax-servlet-api.txt
-rw-r--r--@  1 zhengchenyu  staff  39395 11 11 17:41 LICENSE-jaxb-api.txt
-rw-r--r--@  1 zhengchenyu  staff   1732 11 11 17:41 LICENSE-protobuf.txt
-rw-r--r--@  1 zhengchenyu  staff    774 11 11 17:41 LICENSE-rimraf.txt
-rw-r--r--@  1 zhengchenyu  staff   1154 11 11 17:41 LICENSE-slf4j.txt
-rw-r--r--@  1 zhengchenyu  staff   1360 11 11 17:41 LICENSE-zstd-jni.txt
```

And The files under META-INF/license are as follows:

```
drwxr-xr-x@  6 zhengchenyu  staff    192  5  5  2023 ./
drwxr-xr-x@ 15 zhengchenyu  staff    480 11  9 12:16 ../
-rw-r--r--@  1 zhengchenyu  staff   6121  5  5  2023 LICENSE.aix-netbsd.txt
-rw-r--r--@  1 zhengchenyu  staff  12486  5  5  2023 LICENSE.boringssl.txt
-rw-r--r--@  1 zhengchenyu  staff  11358  5  5  2023 LICENSE.mvn-wrapper.txt
-rw-r--r--@  1 zhengchenyu  staff  11356  5  5  2023 LICENSE.tomcat-native.txt
```

**Comment by jerqi** [comment]
We should merge them. We can copy the files in the `grpc-netty-shaded-1.61.1.jar` to `licenses-binary`.  All the jars with diferent licenses in our project should be contained.

**Comment by zhengchenyu** [comment]
> We should merge them. We can copy the files in the `grpc-netty-shaded-1.61.1.jar` to `licenses-binary`. All the jars with diferent licenses in our project should be contained.

@jerqi  OK, I have merged these. Now the files are as follows:

截屏2024-11-12 12 41 35

**Review by jerqi — APPROVED** [review]

**Pull request merged**
