### PR TITLE
Adjust the memory required times to match grpc max deadline conf

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Adjust the memory required times from 100 to 50 to match the grpc max deadline conf (60s).

### Why are the changes needed?
If the required memory retry time > 60s, the client will cancel the request. That means the required memory exception wont throw to client side. And the server side wont show any related log. 

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by jerqi** [comment]
Like discussion at dev mail list, we will freeze the code and cut 0.6 version branch in September 15, we  will not merge this pr before I cut 0.6 version branch, are you ok?

**Comment by zuston** [comment]
PTAL @jerqi

**Comment by jerqi** [comment]
I can't get the point. Could you give me more explanation?

**Comment by zuston** [comment]
Now the require-memory retry threshold time > 60s in shuffle-server and the client grpc request max-time is 60s, it means that when the shuffle -shuffle memory is tight and the request time reached the 60s, the client side only will show the request timeout exception instead of requiring memory failed log.

**Comment by jerqi** [comment]
> Now the require-memory retry threshold time > 60s in shuffle-server and the client grpc request max-time is 60s, it means that when the shuffle -shuffle memory is tight and the request time reached the 60s, the client side only will show the request timeout exception instead of requiring memory failed log.

OK, make sense, Let's merge it, thanks @zuston

**Review by jerqi — APPROVED** [review]

**Pull request merged**
