### PR TITLE
#1901 feat(script): Support using JVM args to start coordinator/shuffle-server/dashboard

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Support using JVM args for coordinator/shuffle-server/dashboard.

### Why are the changes needed?

Fix: #1901

### Does this PR introduce _any_ user-facing change?

Users can define JVM args within `rss-env.sh`.

like

```
UNIFFLE_DASHBOARD_JAVA_OPTS=" -Dio.netty.leakDetection.level=PARANOID "
UNIFFLE_SHUFFLE_SERVER_JAVA_OPTS=" -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 "
UNIFFLE_COORDINATOR_JAVA_OPTS=""
```

### How was this patch tested?

mvn package and launch each server process using the startup script.

### CODE REVIEW

**Comment by yl09099** [comment]
-Xlog:gc* \
-Xlog:gc+age=trace \
-Xlog:gc+heap=debug \
-Xlog:gc+promotion=trace \
-Xlog:gc+phases=debug \
-Xlog:gc+ref=debug \
-Xlog:gc+start=debug \
This parameter should be removed during the startup of JDK9 and above, which prints a lot of JVM logs that are actually already printed in gc log files.

**Comment by rickyma** [comment]
> -Xlog:gc* -Xlog:gc+age=trace -Xlog:gc+heap=debug -Xlog:gc+promotion=trace -Xlog:gc+phases=debug -Xlog:gc+ref=debug -Xlog:gc+start=debug This parameter should be removed during the startup of JDK9 and above, which prints a lot of JVM logs that are actually already printed in gc log files.

@maobaolong ping~

**Review by rickyma — APPROVED** [review]
LGTM

**Comment by rickyma** [comment]
Thanks for your contribution @maobaolong

**Comment by maobaolong** [comment]
image

**Comment by EnricoMi** [comment]
Can we add these env vars to the docs?

**Comment by maobaolong** [comment]
@EnricoMi With pleasure, I'll add it at once

**Comment by maobaolong** [comment]
> Can we add these env vars to the docs?

@EnricoMi Docs added by https://github.com/apache/incubator-uniffle/pull/1933

**Pull request merged**
