### PR TITLE
[#1269] fix(tez): uniqueMapId may be not unique when more than one fetcher…

### PR DESCRIPTION
**Pull request by zhengchenyu**
### What changes were proposed in this pull request?

make uniqueMapId static.

### Why are the changes needed?

Fix: #1269 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

When flush to disk, may produce this bug. Test and verify on cluster.

### CODE REVIEW

**Comment by zhengchenyu** [comment]
This problem is only related to tez, but no mr. But making uniqueMapId static is indeed more reasonable, so fix mr.

**Comment by jerqi** [comment]
Do  we encounter the concurrency issues if multiple fetchers are used?

**Comment by zhengchenyu** [comment]
> Do we encounter the concurrency issues if multiple fetchers are used?

For TEZ, if auto reduce is enable, a reduce may read multiple partitions, it means multiple fetcher will be used.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @zhengchenyu

**Pull request merged**
