### PR TITLE
[Feature] Support the estimated number of ShuffleServers required.

### PR DESCRIPTION
**Pull request by leixm**
### What changes were proposed in this pull request?
Estimated number of ShuffleServers required.

### Why are the changes needed?
Avoid manually specifying the number of ShuffleServers to improve user experience.

### Does this PR introduce _any_ user-facing change?
Yes.

### How was this patch tested?
UT.

### CODE REVIEW

**Review by jerqi — APPROVED** [review]
LGTM, @zuston Do you have other suggestion?

**Comment by zuston** [comment]
> LGTM, @zuston Do you have other suggestion?

Let me take a look.

**Review by zuston — APPROVED** [review]
LGTM

**Comment by zuston** [comment]
Merged. Thanks @leixm @jerqi .

**Pull request merged**
