### PR TITLE
[#846] feat(cli): Service's start & stop & restart through Cli.

### PR DESCRIPTION
**Pull request by slfan1989**
### What changes were proposed in this pull request?

We support starting and stopping services using CLI commands.

- Command 1: uniffle --daemon start coordinator

```
coordinator start success, is running as process 61743.
```

- Command 2: uniffle --daemon stop coordinator

```
coordinator stop success.
```

- Command 3: uniffle --daemon status coordinator

> If the service is started

```
coordinator is running as process 62087.
```

> If the service is stoped
```
coordinator is stopped.
```

### Why are the changes needed?

Supporting service start and stop functionality using CLI commands is part of this PR.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Testing environment verification.

### CODE REVIEW

**Comment by slfan1989** [comment]
Completed the first version, will continue to improve the code and test it in the testing environment. Currently, it is not ready for review yet.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @slfan1989

**Comment by slfan1989** [comment]
> LGTM, thanks @slfan1989

@jerqi Thank you for helping to review the code! I will add some comments to make the code more readable.

**Comment by jerqi** [comment]
> > LGTM, thanks @slfan1989
> 
> @jerqi Thank you for helping to review the code! I will add some comments to make the code more readable.

ok.

**Review by smallzhongfeng — APPROVED** [review]
LGTM2!

**Comment by jerqi** [comment]
@slfan1989 Is this pr ready for merging?

**Comment by slfan1989** [comment]
@jerqi @smallzhongfeng Can you help to review this pr again? Thank you very much! I and @yl09099 have verified with the production environment.

**Comment by yl09099** [comment]
> @jerqi @smallzhongfeng Can you help to review this pr again? Thank you very much! I and @yl09099 have verified with the production environment.

LGTM.

**Pull request merged**
