### PR TITLE
[#2090] fix(client): use thread-safe list to store the sending status

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Replace LinkedList with CopyOnWriteArrayList to store the sending status

### Why are the changes needed?
Fix: #2090

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI

### CODE REVIEW

**Comment by jerqi** [comment]
CopyOnWriteArrayList is suitable case that read is more, write is less.

**Comment by xianjingfeng** [comment]
> CopyOnWriteArrayList is suitable case that read is more, write is less.

I know, I think this scene is suitable.

**Comment by maobaolong** [comment]
@xianjingfeng Do you think `Collections.synchronizedList` could be better? 

As ShuffleWriteClientImpl#recordFailedBlocks add all the failed blocks to the list, if we replace to `CopyOnWriteArrayList`, the `recordFailedBlocks` performance will get worse as each `add` will cause `new list & copy`.

```java
  void recordFailedBlocks(
      FailedBlockSendTracker blockIdsSendFailTracker,
      Map<ShuffleServerInfo, Map<Integer, Map<Integer, List<ShuffleBlockInfo>>>> serverToBlocks,
      ShuffleServerInfo shuffleServerInfo,
      StatusCode statusCode) {
    serverToBlocks.getOrDefault(shuffleServerInfo, Collections.emptyMap()).values().stream()
        .flatMap(innerMap -> innerMap.values().stream())
        .flatMap(List::stream)
        .forEach(block -> blockIdsSendFailTracker.add(block, shuffleServerInfo, statusCode));
  }
```

I'm not sure this is a read is more, write is less scenario. @zuston If I support `Partition split` leverage `blockIdsSendFailTracker`, do you think the problem getting worse that now?

**Comment by zuston** [comment]
Why not using the `synchronized` to ensure the safety of race condition ? @xianjingfeng I also concern the performance degression when using the CopyOnWrite

**Comment by xianjingfeng** [comment]
> Do you think `Collections.synchronizedList` could be better?

It not thread-safe when iterating over it. @maobaolong 

> Why not using the `synchronized` to ensure the safety of race condition ?

For the job that finally runs successfully, there is at most one element in the list, so I think this performance impact is acceptable.  If you use `synchronized`, we need to pay attention to thread-safe issues when maintaining this part of the code later. `synchronized` is ok for me too.

**Comment by xianjingfeng** [comment]
https://github.com/xianjingfeng/incubator-uniffle/commit/35d0cb485c35dbb3bd6b798e2a04091062be3996 This is a solution with `synchronized`, which I don't think is a good solution. If you think it's OK, I will use this solution. @jerqi @zuston @maobaolong

**Comment by maobaolong** [comment]
> It not thread-safe when iterating over it.

@xianjingfeng Thanks to share this.

And the following trick can resolve the iterator safe issue.

```java
List<Object> list = Collections.synchronizedList(new ArrayList<>());
synchronized (list) {
    Iterator<Object> iterator = list.iterator();
    while (iterator.hasNext()) {
        // ...
    }
}
```


> For the job that finally runs successfully, there is at most one element in the list, so I think this performance impact is acceptable

I'm just implementing a `partition-split` feature leverage on `blockIdsSendFailTracker`, which can invoke the `add` method frequently than before. 

If the existing state `add`  is invoked in low frequent, I'm ok for this PR and I will resolve the performance down issue in that PR.

**Comment by xianjingfeng** [comment]
Changed to use `Collections.synchronizedList` @maobaolong @jerqi @zuston

**Review by maobaolong — APPROVED** [review]
LGTM @xianjingfeng Thanks for this fix!

**Review by zuston — APPROVED** [review]
LGTM.

**Pull request merged**
