### PR TITLE
[ISSUE-48][FEATURE][FOLLOW UP] add docs for operator

### PR DESCRIPTION
**Pull request by wangao1236**
### What changes were proposed in this pull request?
For issue #48 
I add docs about design and usage for operator .

### CODE REVIEW

**Review by zuston — APPROVED** [review]
Great work!

**Comment by jerqi** [comment]
Should we put all the docs into the directory `docs`?

**Comment by jerqi** [comment]
Why do we delete the file `docs/asset/rss_architecture.png`

**Comment by wangao1236** [comment]
> Why do we delete the file `docs/asset/rss_architecture.png`

Sorry, I may have deleted it by mistake, it has been restored

**Review by jerqi — APPROVED** [review]
LGTM

**Pull request merged**
