### PR TITLE
[#1980] feat(coordinator,script): Support coordinator rpc audit log

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Support record audit log for coordinator rpc operation.

### Why are the changes needed?

Fix: #1980

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Start coordinator and server, watch the new `coordinator-rpc-audit.log`

```
[2024-07-29 17:20:18.986] cmd=fetchClientConfV2	statusCode=SUCCESS	appId=N/A	shuffleId=-1	executionTimeUs=6130	
[2024-07-29 17:20:20.900] cmd=heartbeat	statusCode=SUCCESS	appId=N/A	shuffleId=-1	executionTimeUs=618	args{serverNode=XXX-19979}
[2024-07-29 17:20:51.716] cmd=getShuffleAssignments	statusCode=SUCCESS	appId=app-20240729172021-0002_1722244818120	shuffleId=0	executionTimeUs=18097	args{partitionNum=2, partitionNumPerRange=1, replica=1, requiredTags=[ss_v5, GRPC], requiredShuffleServerNumber=-1, faultyServerIds=[], stageId=-1, stageAttemptNumber=0, isReassign=false}
[2024-07-29 17:20:51.981] cmd=registerApplicationInfo	statusCode=SUCCESS	appId=app-20240729172021-0002_1722244818120	shuffleId=-1	executionTimeUs=4142	args{user=user}
[2024-07-29 18:13:44.283] cmd=appHeartbeat	statusCode=SUCCESS	appId=app-20240729173334-0000_1722245612411	shuffleId=-1	executionTimeUs=339	

```

### CODE REVIEW

**Comment by jerqi** [comment]
Could you add a document for this feature?

**Comment by maobaolong** [comment]
> Could you add a document for this feature?

@jerqi Thanks for your review, add to `coordinator_guide.md`

**Comment by maobaolong** [comment]
Flaky test

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.643 s <<< FAILURE! - in org.apache.uniffle.test.RSSStageDynamicServerReWriteTest
Error:  testRSSStageResubmit  Time elapsed: 17.681 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1000> but was: <947>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
```

**Comment by maobaolong** [comment]
@jerqi The flaky test has passed, the config key and description has been append to `coordinator_guide.md`, please take a look if you have time.

**Review by jerqi — APPROVED** [review]

**Comment by rickyma** [comment]
Merged to master. Thanks @maobaolong @jerqi

**Comment by maobaolong** [comment]
@jerqi @rickyma Thanks for your review!

**Pull request merged**
