### PR TITLE
[ISSUE-553] Avoid removing buffer multiple times when clearing resources

### LINKED ISSUE #533: [Improvement] Avoid remove buffer multiple times when clear resource for expired application
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When some appIds remove resources take too much time, `ShuffleBufferManager#removeBufferByShuffleId` will be invoked multiple times for one appId. This will cause memory to be released multiple times. This issue is similar to #459

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Avoid remove buffer multiple times when clear resource

### Why are the changes needed?

This will cause memory to be released multiple times, Fix #533 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need

### CODE REVIEW

**Review by zuston — DISMISSED** [review]

**Comment by zuston** [comment]
LGTM.

> Seems there are multiple instances for this double release.
> Is it possible to add a ut to simulate the long app clean situation and make sure we don't encounter this problem later.
> if is too much trouble, we than defer that in later improvement.

+1. I will merge this if it still has too much work to do when adding tests.

**Comment by xianjingfeng** [comment]
> Seems there are multiple instances for this double release. Is it possible to add a ut to simulate the long app clean situation and make sure we don't encounter this problem later.
> 
> if is too much trouble, we than defer that in later improvement.

I will try to add this ut in this pr.

**Comment by xianjingfeng** [comment]
Similar ut already exist before.

https://github.com/apache/incubator-uniffle/blob/67d155988cd65fffc82a162894628c252184e525/server/src/test/java/org/apache/uniffle/server/ShuffleTaskManagerTest.java#L576

And a new ut is added for this pr. PTAL. @zuston @advancedxy

**Review by zuston — APPROVED** [review]
LGTM

**Comment by zuston** [comment]
Thanks @xianjingfeng @advancedxy. Merged.

**Pull request merged**
