### PR TITLE
[Improvement] No need to use synchronized lock of the method scope when getting client

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
[Improvement] No need to use synchronized lock of the method scope when getting client

### Why are the changes needed?
Avoid unnecessary lock to improve performance.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need.

### CODE REVIEW

**Comment by jerqi** [comment]
I can't tell the difference, we use the `synchronized` lock. Before this patch, we lock the method. After the patch, we lock the class. I think they have the same performance.

**Comment by zuston** [comment]
The lock is just to avoid concurrency conflict on initialization of client. Once Instance is initialized, no need to lock. Right? @jerqi

**Comment by jerqi** [comment]
> The lock is just to avoid concurrency conflict on initialization of client. Once Instance is initialized, no need to lock. Right? @jerqi

I got your point.  But I prefer use LazyHolder
https://github.com/apache/incubator-uniffle/blob/20d39e8455788ce27b97c9a63031d8c42cf64e5f/server/src/main/java/org/apache/uniffle/server/storage/StorageManagerFactory.java#L25

**Comment by zuston** [comment]
Yes. Double-ckeck lock / enum / Inner class are all optional for this requirement. If u prefer inner class. i will update new one later.

**Comment by jerqi** [comment]
> Yes. Double-ckeck lock / enum / Inner class are all optional for this requirement. If u prefer inner class. i will update new one later.

We should unify our style. We use inner class in the other places.

**Review by jerqi — APPROVED** [review]
LGTM

**Pull request merged**
