### PR TITLE
[#1818] fix(spark3): Avoid calling RssShuffleDataIterator.cleanup multiple times

### PR DESCRIPTION
**Pull request by wForget**
### What changes were proposed in this pull request?

Avoid calling `RssShuffleDataIterator.cleanup` multiple times.

### Why are the changes needed?

Fix: #1818

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by rickyma** [comment]
Have you tested it? When will we encounter this issue? Could you add some UTs for this?

**Comment by wForget** [comment]
> Have you tested it? When will we encounter this issue? Could you add some UTs for this?

It happened by chance when I was running integration test for spark3 locally.

**Comment by rickyma** [comment]
Maybe we can place `FunctionUtils` under package `org.apache.uniffle.common.util`? Since it looks more like a common utility?

Also, there are tests failures.

**Comment by wForget** [comment]
> Maybe we can place `FunctionUtils` under package `org.apache.uniffle.common.util`? Since it looks more like a common utility?
> 
> Also, there are tests failures.

It looks like there is scala compatibility issue and we can't put it in common, so I've moved it to spark3 client.

**Comment by rickyma** [comment]
Maybe we can just use pure Java codes, something like:
```
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Supplier;

public class FunctionUtils {

    public static <T> Supplier<T> once(Supplier<T> supplier) {
        return new Supplier<T>() {
            private final AtomicBoolean computed = new AtomicBoolean(false);
            private T value;

            @Override
            public T get() {
                if (computed.compareAndSet(false, true)) {
                    value = supplier.get();
                }
                return value;
            }
        };
    }

    public static void main(String[] args) {
        Supplier<String> supplier = () -> {
            System.out.println("Called only once");
            return "Hello, World!";
        };

        Supplier<String> memoizedSupplier = once(supplier);

        System.out.println(memoizedSupplier.get());
        System.out.println(memoizedSupplier.get());
        System.out.println(memoizedSupplier.get());
    }
}
```

Then we can avoid the Scala compatibility issue. WDYT?

**Comment by wForget** [comment]
> Maybe we can just use pure Java codes, something like:
> 
> ```
> import java.util.concurrent.atomic.AtomicBoolean;
> import java.util.function.Supplier;
> 
> public class FunctionUtils {
> 
>     public static <T> Supplier<T> once(Supplier<T> supplier) {
>         return new Supplier<T>() {
>             private final AtomicBoolean computed = new AtomicBoolean(false);
>             private T value;
> 
>             @Override
>             public T get() {
>                 if (computed.compareAndSet(false, true)) {
>                     value = supplier.get();
>                 }
>                 return value;
>             }
>         };
>     }
> 
>     public static void main(String[] args) {
>         Supplier<String> supplier = () -> {
>             System.out.println("Called only once");
>             return "Hello, World!";
>         };
> 
>         Supplier<String> memoizedSupplier = once(supplier);
> 
>         System.out.println(memoizedSupplier.get());
>         System.out.println(memoizedSupplier.get());
>         System.out.println(memoizedSupplier.get());
>     }
> }
> ```
> 
> Then we can avoid the Scala compatibility issue. WDYT?

`CompletionIterator$.MODULE$.apply` accepts Function0 type

**Comment by rickyma** [comment]
Then I have no more comments, let @advancedxy take another look.

**Comment by wForget** [comment]
> what kind of compatibility issue arise when putting in common?

You can see more details from this failed GA: https://github.com/apache/incubator-uniffle/actions/runs/9640163249/job/26583457745

```
/home/runner/work/incubator-uniffle/incubator-uniffle/client-spark/common/src/main/java/org/apache/spark/shuffle/FunctionUtils.java:[25,30] error: <anonymous org.apache.spark.shuffle.FunctionUtils$1> is not abstract and does not override abstract method apply$mcV$sp() in Function0
```

**Review by zuston — APPROVED** [review]
LGTM.

**Comment by zuston** [comment]
Merged. Thanks @wForget for your contribution and thanks @rickyma @advancedxy  for your review

**Pull request merged**
