### PR TITLE
[MINOR] improvement(ci): add some examples and notice

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

add some examples and notice

### Why are the changes needed?

- To show more use case about how to write PR title
- Notice contributors to remove all the generated comments before review request.

### CODE REVIEW

**Comment by maobaolong** [comment]
@zuston @jerqi Would you like to take a look at this PR template improvement? Thanks.

**Review by zuston — DISMISSED** [review]
lgtm.

**Comment by maobaolong** [comment]
@jerqi How about your idea?

**Comment by jerqi** [comment]
> lgtm.

Which projects adopt `(server)(client)` style?

**Comment by maobaolong** [comment]
@jerqi OKey, I updated it to `(server,client)`

**Review by jerqi — APPROVED** [review]

**Comment by maobaolong** [comment]
@jerqi Thanks for your review, merge it

**Pull request merged**
