### PR TITLE
[#1924] feat(dashboard): Show Thread Dump, Conf and Metrics in DashBoard

### PR DESCRIPTION
**Pull request by kuszz**
### What changes were proposed in this pull request?

Add jetty_port in message ShuffleServerId.
Modify dashboard, add some link in dashboard
企业微信截图_ede78628-56ac-4b7e-86ab-84b224da7ce4
企业微信截图_88b2c855-68e4-4054-94a3-d730f074a4b9

### Why are the changes needed?

Enhance dashboard capabilities

Fix: #1924

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by maobaolong** [comment]
@kuszz This is an interesting feature, but would you like to fix the failed ci and paste some more screenshot

**Comment by kuszz** [comment]
> @kuszz This is an interesting feature, but would you like to fix the failed ci and paste some more screenshot

done

**Comment by jerqi** [comment]
@kuszz Could you modify the title of this pull request?

**Comment by kuszz** [comment]
> @kuszz Could you modify the title of this pull request?

@jerqi Sure, is this title okay now, or another one?

**Comment by jerqi** [comment]
> > @kuszz Could you modify the title of this pull request?
> 
> @jerqi Sure, is this title okay now, or another one?

You should follow the format of other pull requests like [#issue id] feat(dashboard): Show Thread Dump, Conf and Metrics in DashBoard

**Comment by kuszz** [comment]
> > > @kuszz Could you modify the title of this pull request?
> > 
> > 
> > @jerqi Sure, is this title okay now, or another one?
> 
> You should follow the format of other pull requests like [#issue id] feat(dashboard): Show Thread Dump, Conf and Metrics in DashBoard

@jerqi done

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by maobaolong — APPROVED** [review]
LGTM

**Comment by yl09099** [comment]
This PR should not be written in the Vue2 way, I think asynchronous method handling should be handled on the page to control exceptions.

**Pull request merged**
