### PR TITLE
[#2048] feat(coordinator): Introduce dashboard page in dashboard web ui

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Introduce dashboard page in dashboard web ui to show the version, start time and other information about dashboard.

### Why are the changes needed?

Fix: #2048

### Does this PR introduce _any_ user-facing change?

Dashboard UI

### How was this patch tested?

image

### CODE REVIEW

**Comment by zuston** [comment]
Could you help review this @yl09099 @xianjingfeng

**Comment by yl09099** [comment]
Isn’t it too monotonous to make a separate page display version and a startup time for the dashboard?
My humble opinion.

**Comment by maobaolong** [comment]
@yl09099 Thanks for your reply. I do agree with your opinion for now, the main motivation of this PR is displaying the version and start time of dashboard process in the dashboard ui, but I can make it display more information in the dashboard page, e.g. config table. I believe it can be better if we add a config table.

**Comment by maobaolong** [comment]
image

I add config table to dashboard page, PTAL @yl09099

**Review by xianjingfeng — APPROVED** [review]
LGTM

**Comment by yl09099** [comment]
LGTM

**Comment by zuston** [comment]
Thanks @maobaolong @yl09099 @xianjingfeng

**Pull request merged**
