### PR TITLE
[MINOR] Improve(script): Change intellij launch config file name and local-dev conf folder

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

- Copy local_dev conf to .idea folder which a folder in `.gitignore`, so, local_dev conf changes are not tracked by git.
- Remove the xml suffix of `runConfigurations/xxx.xml`, if not, intellij idea will find it and load the configurations into idea, after that, any idea launch configuration change will persist to these files, what is not we want. Remove the xml suffix can make idea don't treat these files as launch configuration files.

### Why are the changes needed?

Without this change, any local purpose change will tracked by git, this make contributors busy to revert changes or push local changes to git repository by accident.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Just run the `incubator-uniffle/dev/intellij/install-runconfig.sh`

### CODE REVIEW

**Comment by jerqi** [comment]
Could we move local_dev conf to the directory dev? Because conf directory will be packaged to the release package.

**Comment by maobaolong** [comment]
@jerqi Good suggestion!

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi Thanks for your review!

**Pull request merged**
