### PR TITLE
[FOLLOWUP][#2105] Fix memory leak caused by duplicate blocks when using ShuffleBufferWithLinkedList

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Fix memory leak issue after the data structure of `blocks` changed from `list` to `set`.

### Why are the changes needed?

Fix: #2105

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need.

### CODE REVIEW

**Comment by maobaolong** [comment]
@zuston @zhengchenyu @lwllvyb @yl09099 Would you like to take a look at this PR?

**Review by zuston — APPROVED** [review]
LGTM.

**Review by zhengchenyu — APPROVED** [review]
LGTM +1

**Comment by yl09099** [comment]
LGTM +1

**Comment by maobaolong** [comment]
The failed test is a flaky test `Quorum#case10`
```
Error:  case10  Time elapsed: 184.153 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at org.apache.uniffle.test.QuorumTest.case10(QuorumTest.java:948)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Pull request merged**
