### PR TITLE
Execute start script with nohup

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Execute start script with nohup

### Why are the changes needed?

Process don't exit if exec start script using ansible. Therefore, we can't do batch start operation for this.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Have already verify in our production enviroment.

### CODE REVIEW

**Comment by jerqi** [comment]
@zuston I don't have ansible environment, Could you help me review and verify this path?

**Comment by zuston** [comment]
I use the shell module of ansible to start the shuffle server without this PR, it wont block. command as:  `ansible -i hosts_xxx -m shell -a "./start-shuffle-server.sh"`

Could u help provide some detailed info that which ansible module dont work? I will test it. @xianjingfeng

**Comment by xianjingfeng** [comment]
> I use the shell module of ansible to start the shuffle server without this PR, it wont block. command as: `ansible -i hosts_xxx -m shell -a "./start-shuffle-server.sh"`
> 
> Could u help provide some detailed info that which ansible module dont work? I will test it. @xianjingfeng

I forget. I'll ask my colleague next week. I tried it myself just now, and i found the jvm will exit immediately without this pr.

**Comment by xianjingfeng** [comment]
@zuston  Blocked is because we have made a layer of encapsulation for ansible. We will check if the process start successful. Process will not start successful by using native ansible without this pr.

**Comment by zuston** [comment]
But the process could be started successfully by native ansible for me.

**Comment by jerqi** [comment]
If this pr only solve the issue of company's internal specific implement, I prefer not merging it.

**Comment by xianjingfeng** [comment]
@jerqi @zuston 
截图202282134548

**Comment by jerqi** [comment]
@zuston What's your suggestion?

**Comment by pan3793** [comment]
Hadoop, Spark, Hive, Trino support run service both on frontend or as deamon, can we follow them?

**Comment by zuston** [comment]
I also use the ansible of 2.9.27 but no such problems. @xianjingfeng And i dont see any blocking in your sceenshot.

> Hadoop, Spark, Hive, and Trino support run service both on frontend or as daemon, can we follow them?

Agree with u @pan3793

**Comment by xianjingfeng** [comment]
> And i dont see any blocking in your sceenshot.

Not blocked, jvm process have not start if start by ansible

**Comment by zuston** [comment]
Got your point. @xianjingfeng But i think we should dig the cause rather than using the nohup directly? But i have no solutions currently

**Pull request closed without merging**
