### PR TITLE
[#1261] fix(spark): Throw out InterruptedException for sleep in requestExecutorMemory

### PR DESCRIPTION
**Pull request by wForget**
### What changes were proposed in this pull request?

Pass InterruptedException in requestExecutorMemory.

### Why are the changes needed?

Fix:  #1261

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by summaryzb** [comment]
Good catch

**Review by zuston — APPROVED** [review]
LGTM. Merged.

**Comment by jerqi** [comment]
@zuston Should we merge this to branch 0.8, too?

**Comment by zuston** [comment]
> @zuston Should we merge this to branch 0.8, too?

I think yes.

**Pull request merged**
