### PR TITLE
[#2145] feat(server): The server-side supports choosing Netty's ByteBufAllocator.

### PR DESCRIPTION
**Pull request by zhengchenyu**
### What changes were proposed in this pull request?

The server-side supports choosing Netty's ByteBufAllocator.

### Why are the changes needed?

Fix: #2145 

### Does this PR introduce _any_ user-facing change?

Introduce rss.server.netty.pooled.allocator.enabled to choose allocator.

### How was this patch tested?

test in cluster.

### CODE REVIEW

**Comment by rickyma** [comment]
The Uniffle server does not support `PooledByteBufAllocator` for now. You can refer to https://github.com/apache/incubator-uniffle/pull/1534.

**Comment by zhengchenyu** [comment]
> The Uniffle server does not support `PooledByteBufAllocator` for now. You can refer to #1534.

Thanks for you quick reply! It is just a draft.
I think you mean that if we used pooled allocator, we allocate chunkSize, but it is not matched with usedMemory in uniffle, then may result to OOM. Am I correct in my understanding?
If so, just close this pr.

**Comment by rickyma** [comment]
Yes, you are right.

**Comment by zhengchenyu** [comment]
> Yes, you are right.

Thanks for your reply! I will revert it in our repo, then I'm trying to use mimalloc that you talked about earlier.

**Comment by xianjingfeng** [comment]
I need this feature. I found that in our production environment, memory allocation and deallocation are very slow on machines with large memory(1.5T). We will reserve sufficient memory, so I think the risk of OOM is relatively low for us. So I think this feature can be used as an option. cc @rickyma @zhengchenyu @jerqi @zuston

**Comment by zuston** [comment]
> I need this feature. I found that in our production environment, memory allocation and deallocation are very slow on the machines with large memory(1.5T). We will reserve sufficient memory, so I think the risk of OOM is relatively low for us. So I think this feature can be used as an option. cc @rickyma @zhengchenyu @jerqi @zuston

Make sense to me. Let @zhengchenyu take a deep look.

**Pull request closed without merging**
