### PR TITLE
[#80] feat: Support shuffle server decommission

### LINKED ISSUE #80: [Feature Request]  Support shuffle server decommissioned
kill process is not graceful, so we need shuffle server support decommissioned

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Support shuffle server decommission and introduce a framework to support other features which are for managing shuffle servers, such as UpdateConfiguration and Upgrade.
Design doc:  https://docs.google.com/document/d/1p1PksBN2LJ-OtGEHvdyEuH9b1Mv1aD_exMPl4TNaTs0/edit?usp=sharing
### Why are the changes needed?

At present, if we need to shutdown a shuffle server, we need to add the shuffle server instance to exclude-node-file and wait until all applications finish and then kill it. And if we need to start it again, we need to remove it from the exclude-node-file first. This process is very inconvenient, so we need a new graceful way to support shuffle server decommission.
Fix #80 
### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UTs

### CODE REVIEW

**Comment by kaijchen** [comment]
Thanks a lot to @xianjingfeng for working on this. The current PR looks a little large. Is it possible to break it down into several pieces?

IMO it can be split into 3 pieces:

1. Decommission logic on shuffle server.
2. The RPC and heartbeat between coordinator and shuffle server.
3. REST api to coordinator.

**Comment by xianjingfeng** [comment]
> Thanks a lot to @xianjingfeng for working on this. The current PR looks a little large. Is it possible to break it down into several pieces?
> 
> IMO it can be split into 3 pieces:
> 
> 1. Decommission logic on shuffle server.
> 2. The RPC and heartbeat between coordinator and shuffle server.
> 3. REST api to coordinator.

Agree. The first part: #606

**Comment by zuston** [comment]
> @zuston when do you think that the new release would be started?

I will checkout a new release branch of `branch-0.7` from the commit id of `80c12a7ac3c159583c2788e9735ce171f3b0a008` https://github.com/apache/incubator-uniffle/commit/80c12a7ac3c159583c2788e9735ce171f3b0a008 firstly. WDYT? @advancedxy @jerqi

**Comment by kaijchen** [comment]
> I will checkout a new release branch of `branch-0.7` from the commit id of `80c12a7ac3c159583c2788e9735ce171f3b0a008` [80c12a7](https://github.com/apache/incubator-uniffle/commit/80c12a7ac3c159583c2788e9735ce171f3b0a008) firstly. WDYT? @advancedxy @jerqi

@advancedxy @zuston Let's discuss things about 0.7.0 release in #611

**Pull request closed without merging**
