### PR TITLE
[MINOR] Remove meaningless string concatenation

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

1. Remove meaningless string concatenation.
2. Use slf4j instead of apache commons logging.

### Why are the changes needed?

Better readablity and performance, and reduce maintenance complexity.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Review by EnricoMi — APPROVED** [review]
I like this, thanks!

**Comment by EnricoMi** [comment]
Is this exhaustive? Are this all instances of pointless string concatenations?

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
Could you help merge this? @EnricoMi , I think you have permission to operate this.

**Comment by zuston** [comment]
We hope the description could be attached in the commit log when you operate `squal and commit` button. @EnricoMi

**Comment by EnricoMi** [comment]
You mean the description of the pull request?

**Comment by EnricoMi** [comment]
Sorry for that! This should be configured as the default squash behaviour then, no copy-paste required:
image

**Pull request merged**
