### PR TITLE
[BUG][AQE][LocalOrder] Fix the bug of missed data due to block sorting

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

1. Create a extra reference copy of inFlushed blocks to avoid breaking down original sequence,  if not, it will cause missed data when reading due to the sequence reading when getting memory data.

### Why are the changes needed?

Fix the bug of missed data due to block sorting

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

1. UTs

### CODE REVIEW

**Comment by zuston** [comment]
PTAL @jerqi

**Review by jerqi — APPROVED** [review]
LGTM, thanks @zuston , wait for CI.

**Comment by zuston** [comment]
Merged. Thanks @jerqi for catching this bug.

**Comment by zuston** [comment]
> https://github.com/apache/incubator-uniffle/actions/runs/3524774587/jobs/5910627949?

#350

**Pull request merged**
