### PR TITLE
[MINOR] Remove commiters from collaborators

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
Remove commiters from collaborators

### Why are the changes needed?
Xianjing Feng became our commiter, let us remove him from collaborators.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need

### CODE REVIEW

**Comment by jerqi** [comment]
@xianjingfeng Could you review and merge this pr?

**Review by xianjingfeng — APPROVED** [review]
LGTM

**Comment by jerqi** [comment]
@xianjingfeng We usually add the commit message like
企业微信截图_e6096dc4-a752-4635-bcb8-f3468321efc9

**Comment by xianjingfeng** [comment]
> @xianjingfeng We usually add the commit message like 企业微信截图_e6096dc4-a752-4635-bcb8-f3468321efc9

Get

**Pull request merged**
