### PR TITLE
[FOLLOWUP] feat(docs): Add documents for the two bufferSize configs.

### PR DESCRIPTION
**Pull request by lwllvyb**
### What changes were proposed in this pull request?

Add documents for the two bufferSize configs in server_guide.md.

### Why are the changes needed?

Fix: #2209 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested locally.

### CODE REVIEW

**Comment by jerqi** [comment]
Maybe this could be used for HDFS, too.

**Comment by lwllvyb** [comment]
> Maybe this could be used for HDFS, too.

I will add an new issue to handle with the HDFS.

**Comment by lwllvyb** [comment]
Ping @jerqi

**Review by jerqi — APPROVED** [review]
LGTM.

**Pull request closed without merging**
