### PR TITLE
[#1385] improvement: Improve log4j appender layout pattern

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Improve the log4j appender layout pattern, by adding the full logger name and code line number.

### Why are the changes needed?

For [#1385](https://github.com/apache/incubator-uniffle/issues/1385)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

By running the process successfully and check the log4j output.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL @jerqi

**Review by jerqi — APPROVED** [review]
LGTM. thanks @rickyma

**Comment by zuston** [comment]
I will -1 for this PR, the line number will drop huge performance.

**Comment by rickyma** [comment]
@zuston You're right. I'll remove the line number. Any other suggestions here? Thanks.

**Comment by zuston** [comment]
Can you give the comparison logs of after and before this patch ? @rickyma

**Comment by rickyma** [comment]
PTAL @zuston 

Before this patch:
[INFO] 2023-12-23 01:09:36,830 main ShuffleServer start - Shuffle server start successfully!

After this patch:
[2023-12-23 01:09:36.830] [main] [INFO] org.apache.uniffle.server.ShuffleServer.start - Shuffle server start successfully!

Also, I think the default MaxFileSize 50MB is too small, wouldn't it be better to set it to maybe 2GB?

**Comment by zuston** [comment]
> Before this patch:
[INFO] 2023-12-23 01:09:36,830 main ShuffleServer start - Shuffle server start successfully!

After this patch:
[2023-12-23 01:09:36.830] [main] [INFO] org.apache.uniffle.server.ShuffleServer.start - Shuffle server start successfully!


I think the original log is enough, too long package name is not necessary that will occupy too much space

> Also, I think the default MaxFileSize 50MB is too small, wouldn't it be better to set it to maybe 2GB?

This is OK for me.

**Comment by rickyma** [comment]
Updated. PTAL @zuston 

Before this patch:
[INFO] 2023-12-23 01:09:36,830 main ShuffleServer start - Shuffle server start successfully!
MaxFileSize = 50MB

After this patch:
[2023-12-23 01:09:36.830] [main] [INFO] ShuffleServer.start - Shuffle server start successfully!
MaxFileSize = 2GB

**Review by zuston — APPROVED** [review]
LGTM. Thanks for your contribution @rickyma

**Review by jerqi — APPROVED** [review]
LGTM.

**Pull request merged**
