### PR TITLE
[WIP] Add offline api for shuffle server

### PR DESCRIPTION
**Pull request by wForget**
### What changes were proposed in this pull request?

Add offline api for shuffle server

### Why are the changes needed?

Make shuffle server offline easier.

### Does this PR introduce _any_ user-facing change?

Yes, add a offline rest api for shuffle server

### How was this patch tested?

added org.apache.uniffle.test.ShuffleServerApiTest integration test.

### CODE REVIEW

**Comment by jerqi** [comment]
Shuffle server already have provide a metric http api.  The metric `app_num_with_node` will tell you how many apps there are on the node. We recommend that we use this metric to judge whether to be able to stop the server. Moreover,  we are working on a Uniffle K8S operator. Basic tests passed currently, and we will open source it soon.
If you want to add rest api to stop server, is it possible to imitate the `CommonMetricsServlet` to create another Servlet?
If we want to add some Servlets to control shuffle server's behavior,  do we need some more detailed discussions?

**Comment by wForget** [comment]
@jerqi Thank you for your reply

> Shuffle server already have provide a metric http api. The metric app_num_with_node will tell you how many apps there are on the node. We recommend that we use this metric to judge whether to be able to stop the server.

When we want to redeploy the shuffle server, we need to mark the server to be offline first, and then stop it when there is no application handle in the shuffle server.
I want to implement an  rest api in the shuffle server that first marks the server as offline, then starts a check thread that checks if the number of applications being processed by the shuffle server is empty, and then stops it.

> If you want to add rest api to stop server, is it possible to imitate the CommonMetricsServlet to create another Servlet?

Using HttpServlet should work, but the implemented code looks complicated.
Is this feature reasonable? If reasonable I would use HttpServlet to implement it.

> If we want to add some Servlets to control shuffle server's behavior, do we need some more detailed discussions?

Yes, looks like more details need to be discussed, I will open an issue to follow up it.

**Comment by jerqi** [comment]
I understand that you need  a `rolling upgrade` feature. I think it's not good enough that we just add an offline api. In our plan, we want to  accomplish this feature by k8s operator. For the standalone mode, we don't have the plans, you can open another issue to discuss this question. And it's also necessary to do some surveys about this feature.

**Comment by wForget** [comment]
> I understand that you need a `rolling upgrade` feature. I think it's not good enough that we just add an offline api. In our plan, we want to accomplish this feature by k8s operator. For the standalone mode, we don't have the plans, you can open another issue to discuss this question. And it's also necessary to do some surveys about this feature.

Got it, thanks, I will close this pr first.

**Pull request closed without merging**
