### PR TITLE
[ISSUE-512][Operator] Bump golang to 1.17

### LINKED ISSUE #512: [Bug] Golang CI failed
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
# golang.org/x/sys/unix
Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.4.0/unix/syscall.go:83:16: undefined: unsafe.Slice
Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.4.0/unix/syscall_linux.go:2270:9: undefined: unsafe.Slice
Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.4.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.4.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice

```
Detailed info could be found in https://github.com/apache/incubator-uniffle/actions/runs/4031027397/jobs/6930075459

### Affects Version(s)

master

### Uniffle Server Log Output

_No response_

### Uniffle Engine Log Output

_No response_

### Uniffle Server Configurations

_No response_

### Uniffle Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes were proposed in this pull request?

Bump go version of `deploy/kubernetes/operator` to 1.17.

### Why are the changes needed?

Fix #512.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.

### CODE REVIEW

**Comment by wangao1236** [comment]
What is the specific smaller version of the previous golang? My local version is go-1.16.15.

**Comment by kaijchen** [comment]
> What is the specific smaller version of the previous golang? My local version is go-1.16.15.

The revision doesn't matter. The new interface was introduced in go std library 1.17.

**Comment by kaijchen** [comment]
> Let's address the golang issue in #491 ?
> 
> I have updated the related files, and it should be passing.

It won't work if you don't change go version in go.mod

**Comment by kaijchen** [comment]
> Yeah，I found that and it’s also addressed.

Sorry, I didn't see that. However, I don't think "better **build system** support" should change the go version of a project.
Maybe find a better title or just do one thing at a time?

**Comment by zuston** [comment]
> > Yeah，I found that and it’s also addressed.
> 
> Sorry, I didn't see that. However, I don't think "better **build system** support" should change the go version of a project. Maybe find a better title or just do one thing at a time?

We could push forward this PR quickly to avoid CI failure later

**Comment by kaijchen** [comment]
> I'm ok to change the PR/commit title.
> 
> But after a second thought, it could be better to merge this quickly. This is the simplest fix and it has the same effect/result as disable k8s ut temporary. We could address other related changes in followup pr or in #491.
> 
> Let's merge this quickly then? @kaijchen @zuston

Sure, thanks for the review. Bumping the golang version is a quick fix here.
To fully address the problem, we should find a way to anchor versions of the transitive dependencies.

**Review by zuston — APPROVED** [review]

**Comment by kaijchen** [comment]
Thanks @advancedxy and @zuston for the review.

**Comment by kaijchen** [comment]
> It won't work if you don't change go version in go.mod

Sorry I forgot to include the go.mod bump in this PR.
Seems it works without changing go version in go.mod.

**Pull request merged**
