### PR TITLE
[#951] build(operator): Add the HADOOP_VERSION for Docker image.

### PR DESCRIPTION
**Pull request by qijiale76**
### What changes were proposed in this pull request?
Add the HADOOP_VERSION for Docker image.

### Why are the changes needed?

Fix: #951 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
By hand.

### CODE REVIEW

**Comment by jerqi** [comment]
@qijiale76 Could you correct the description of pr?

**Comment by jerqi** [comment]
@connorlwilkes Could you help review this pr if you have time?

**Comment by zuston** [comment]
I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird

**Comment by jerqi** [comment]
> I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird

Shuffle Server must use the HDFS jars. Because some configuration use HDFS jars.

**Comment by zuston** [comment]
> > I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird
> 
> Shuffle Server must use the HDFS jars. Because some configuration use HDFS jars.

Oh, I forgot this. This should be optimized in the later PR.

**Comment by zhengchenyu** [comment]
> I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird

@zuston 

Hadoop version is introduced by me in #896  
I think we should bind hadoop version, even if we don't use HDFS. We know mapreduce, spark and tez depend on hadoop. Because the API is changed, some version of computing framework may not be compatibility with some verison of hadoop. 
In production cluster, use the computing framework which is not  compatibility with hadoop may produce many unexpected error.

**Comment by zuston** [comment]
> > I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird
> 
> @zuston
> 
> Hadoop version is introduced by me in #896 I think we should bind hadoop version, even if we don't use HDFS. We know mapreduce, spark and tez depend on hadoop. Because the API is changed, some version of computing framework may not be compatibility with some verison of hadoop. In production cluster, use the computing framework which is not compatibility with hadoop may produce many unexpected error.

You are right. I have checked that all the spark distribution are all bind to hadoop.

**Comment by zhengchenyu** [comment]
> > > I'm not sure is it necessary to bind hadoop version with image. If user don't use HDFS, this is weird
> > 
> > 
> > @zuston
> > Hadoop version is introduced by me in #896 I think we should bind hadoop version, even if we don't use HDFS. We know mapreduce, spark and tez depend on hadoop. Because the API is changed, some version of computing framework may not be compatibility with some verison of hadoop. In production cluster, use the computing framework which is not compatibility with hadoop may produce many unexpected error.
> 
> You are right. I have checked that all the spark distribution are all bind to hadoop.

I just copy spark! ^_^

**Review by jerqi — APPROVED** [review]
LGTM, thanks all.

**Pull request merged**
