### PR TITLE
[#1858] feat(spark): Introduce a fine-grained force commit switch

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Introduce a fine-grained force commit switch.

### Why are the changes needed?

For https://github.com/apache/incubator-uniffle/issues/1858.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by rickyma** [comment]
For a single app, indeed there is a performance decrease, but if running a large number of apps simultaneously, the overall throughput remains the same. We provide an optional choice, and the default value is false.

**Comment by jerqi** [comment]
> For a single app, indeed there is a performance decrease, but if running a large number of apps simultaneously, the overall throughput remains the same. We provide an optional choice, and the default value is false.

If we running multiple applications, the performance will be worse.

**Comment by rickyma** [comment]
This can only indicate that there are not enough running apps. When there are enough apps, no app's shuffle data can stay in memory for a long time. Therefore, in this scenario, the performance will not be affected very much, and only in this scenario will we consider enabling this switch.

**Comment by rickyma** [comment]
Closed. We don't use this flag anymore.

**Pull request closed without merging**
