### PR TITLE
[#1655] Bump version to 0.10.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?

Bump version to `0.10.0-SNAPSHOT`.

    sed -i "s%<version>0.9.0-SNAPSHOT</version>%<version>0.10.0-SNAPSHOT</version>%" $(grep -l "<groupId>org.apache.uniffle</groupId>" $(find . -name pom.xml))

### Why are the changes needed?
Releasing 0.9.0 from `branch-0.9`.

Fix: #1655

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Not needed.

### CODE REVIEW

**Comment by zuston** [comment]
How about using the command of `mvn versions:set -DnewVersion=xx ` to update?

**Comment by EnricoMi** [comment]
> How about using the command of `mvn versions:set -DnewVersion=xx ` to update?

That is handy. Unfortunately, this does not upgrade `client-mr/hadoop2.8/pom.xml` and `client-mr/hadoop3.2/pom.xml`.

**Review by zuston — APPROVED** [review]
LGTM.

**Comment by jerqi** [comment]
> > How about using the command of `mvn versions:set -DnewVersion=xx ` to update?
> 
> That is handy. Unfortunately, this does not upgrade `client-mr/hadoop2.8/pom.xml` and `client-mr/hadoop3.2/pom.xml`.

Do you know the root of cause why they aren't upgraded?

**Comment by EnricoMi** [comment]
> > > How about using the command of `mvn versions:set -DnewVersion=xx ` to update?
> > 
> > 
> > That is handy. Unfortunately, this does not upgrade `client-mr/hadoop2.8/pom.xml` and `client-mr/hadoop3.2/pom.xml`.
> 
> Do you know the root of cause why they aren't upgraded?

Yes, the root POM references the hadoop modules using a variable, which `versions:set` cannot resolve:

    <module>client-mr/hadoop${hadoop.short.version}</module>

One solution would be to add a profile that references both hadoop modules explicitly (without variables), while that profile is not used for anything useful (other than running `mvn versions:set`).

**Comment by jerqi** [comment]
> > > > How about using the command of `mvn versions:set -DnewVersion=xx ` to update?
> > > 
> > > 
> > > That is handy. Unfortunately, this does not upgrade `client-mr/hadoop2.8/pom.xml` and `client-mr/hadoop3.2/pom.xml`.
> > 
> > 
> > Do you know the root of cause why they aren't upgraded?
> 
> Yes, the root POM references the hadoop modules using a variable, which `versions:set` cannot resolve:
> 
> ```
> <module>client-mr/hadoop${hadoop.short.version}</module>
> ```
> 
> One solution would be to add a profile that references both hadoop modules explicitly (without variables), while that profile is not used for anything useful (other than running `mvn versions:set`).

I got it. Thanks. It's ok for me now.

**Comment by zuston** [comment]
Merged. Thanks @EnricoMi

**Pull request merged**
