### PR TITLE
[#1698] fix(test): Increase tests running memory for better stability

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Increase tests running memory for better stability.

### Why are the changes needed?

Fix: https://github.com/apache/incubator-uniffle/issues/1698.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unnecessary.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL @zuston @jerqi

**Comment by rickyma** [comment]
What's your idea? Gently ping @zuston @jerqi

**Review by zuston — APPROVED** [review]
LGTM

**Comment by jerqi** [comment]
@zuston Have you committed this to branch 0.9?

**Comment by jerqi** [comment]
When you merge a pull request, you should say which branch is merged. like
```
merged to master & branch 0.9.
```

**Comment by zuston** [comment]
> @zuston When you merge a pull request, you should say which branch is merged. like
> 
> ```
> merged to master & branch 0.9.
> ```

Needn't. Like this, if this PR is cherry-picked to other branches, github will show this.

image

BTW. Some PRs for me is not necessary to cherry-pick to branch-0.9 . If you want this, feel free to tell me advancely

**Comment by jerqi** [comment]
> > @zuston When you merge a pull request, you should say which branch is merged. like
> > ```
> > merged to master & branch 0.9.
> > ```
> 
> Needn't. Like this, if this PR is cherry-picked to other branches, github will show this.
> 
> image
> 
> BTW. Some PRs for me is not necessary to cherry-pick to branch-0.9 . If you want this, feel free to tell me advancely

If one pull request is a fix, this must be back port to the branch unless the change has great affect. Improvement is optional. We would better to avoid backing port feature.

**Pull request merged**
