### PR TITLE
[#1401] improvement(dashboard): Make startup scripts support JDK9 or later.

### PR DESCRIPTION
**Pull request by yl09099**
### What changes were proposed in this pull request?

The script startup parameters are outdated when the dashboard is booted with an advanced JDK version.

The issues are as follows：
[0.001s][warning][gc] -XX:+PrintGC is deprecated. Will use -Xlog:gc instead.
[0.001s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
-XX:ConcGCThreads=5 -XX:G1ConcRefinementThreads=20 -XX:GCDrainStackTargetSize=64 -XX:+IgnoreUnrecognizedVMOptions -XX:InitialHeapSize=42949672960 -XX:InitiatingHeapOccupancyPercent=45 -XX:MaxGCPauseMillis=200 -XX:MaxHeapSize=42949672960 -XX:ParallelGCThreads=20 -XX:+PrintCommandLineFlags -XX:+PrintGC -XX:+PrintGCDetails -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseG1GC

### Why are the changes needed?

Fix: #1401 
### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UT.

### CODE REVIEW

**Comment by yl09099** [comment]
@rickyma PATL.

**Review by rickyma — APPROVED** [review]
LGTM.

**Comment by rickyma** [comment]
Wait one day for others to take a look.

**Review by jerqi — APPROVED** [review]

**Comment by rickyma** [comment]
Merged to master. Thanks @yl09099 @jerqi

**Pull request merged**
