### PR TITLE
Fix some hyperlink in README.md

### PR DESCRIPTION
**Pull request by daugraph**
### What changes were proposed in this pull request?
Fix some hyperlink error in README.md 

### Why are the changes needed?
Fix some hyperlink error

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manual

### CODE REVIEW

**Comment by frankliee** [comment]
Thanks for your contribution.
Could you change all Firestorm to Uniffle?

**Comment by daugraph** [comment]
>

**Comment by daugraph** [comment]
> 

Resolved

**Comment by daugraph** [comment]
Thanks for your review, everything is ok now

**Review by jerqi — APPROVED** [review]

**Comment by jerqi** [comment]
@daugraph Thanks for your contribution.

**Pull request merged**
