### PR TITLE
[MINOR] feat(server): Introduce metrics related bitmaps(committedBlockIds/cachedBlockIds/partitionToBlockIds)

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Introduce metrics related bitmaps.

### Why are the changes needed?

Insight the block bitmap related count.

Fix: # (issue)

### Does this PR introduce _any_ user-facing change?

- committed_block_count
- reported_block_count
- cached_block_count

### How was this patch tested?

Locally.

image

### CODE REVIEW

**Comment by maobaolong** [comment]
@zuston Would you like to take a look at this PR? Thank you!

**Comment by maobaolong** [comment]
@xianjingfeng @jerqi Look forward to your review, thanks!

**Comment by jerqi** [comment]
Will this pull request be affected by https://github.com/apache/incubator-uniffle/pull/2196?

**Comment by maobaolong** [comment]
@jerqi yes, this will conflict if merge #2196, but doesn't matter, I will resolve it

**Comment by maobaolong** [comment]
@jerqi Sorry for the mistake reply, this PR have no relative to the #2196

**Comment by jerqi** [comment]
> @jerqi Sorry for the mistake reply, these metrics can show the effect of #2196.
> 
> For our scenario, we use `LOCAL_MEMORY` storage type, so the `committed_block_count` and `cached_block_count` is `0` after combine these two PRs. I tested on our internal cluster.

LGTM if it won't throw an error.

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi yeah, it do not throw exception

**Pull request merged**
