### PR TITLE
[#1966] improvement(script): Move rss-env.sh to conf folder

### LINKED ISSUE #1966: [Improvement] Move rss-env.sh to conf folder
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Move the rss-env.sh into conf folder as it is a part of config

### How should we improve?

Just move it.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Move rss-env.sh to conf folder.

### Why are the changes needed?

Fix #1966

`rss-env.sh` is a part of config file, it is mutable, we should maintain it within config server rather than `bin` folder

### Does this PR introduce _any_ user-facing change?

`rss-env.sh` is moved to `conf` folder.

### How was this patch tested?

Start all components successfully.

### CODE REVIEW

**Comment by maobaolong** [comment]
@advancedxy This is a single purpose PR, it just move `rss-env.sh` to conf folder, PTAL

**Comment by maobaolong** [comment]
@advancedxy Thanks for your suggested change, I pasted it into rss-env.sh, PTAL.

**Comment by rickyma** [comment]
This is not minor. Please create an issue to track this.

**Comment by maobaolong** [comment]
> This is not minor. Please create an issue to track this.

Done

**Comment by rickyma** [comment]
Merged to master. 
Thanks for your contribution. @maobaolong 
Thanks for your review. @advancedxy

**Comment by maobaolong** [comment]
@rickyma @advancedxy Thanks for your review！

**Pull request merged**
