### PR TITLE
[MINOR] improvement(server): Dynamic conf support of server memory watermark

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Support dynamic update the conf of high/low water mark.

### Why are the changes needed?

It can be easy to tune the server online without restart leverage this.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested Locally.

```Console
➜  ~ curl -X POST http://localhost:19948/api/shuffleServer/confOps/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.memory.shuffle.highWaterMark.percentage": "0.5", "rss.server.memory.shuffle.lowWaterMark.percentage": "0.1"}}'

temporarily effective until restart: Update successfully
```

server.log

```
[2024-11-03 21:29:20.660] [Jetty-5] [INFO] ConfOpsResource - Dynamic updating ConfVO{update={rss.server.memory.shuffle.highWaterMark.percentage=0.5, rss.server.memory.shuffle.lowWaterMark.percentage=0.1}, delete=[]}
```

snapshot_b6b93cf5-bf97-4efb-9f20-f106c9278b27

### CODE REVIEW

**Comment by jerqi** [comment]
Will the config option be written back to the configuration file?

**Comment by maobaolong** [comment]
@jerqi No, reconfig through restapi is a  temporarily way, this can be use when we tuning the configs or in an emergency to avoid restart server.

**Comment by jerqi** [comment]
> @jerqi No, reconfig through restapi is a temporarily way, this can be use when we tuning the configs or in an emergency to avoid restart server.

Maybe you should add `temporarily` key word in the URL.

**Comment by maobaolong** [comment]
`curl -X POST http://localhost:19948/api/shuffleServer/confOps/update `
->
`curl -X POST http://localhost:19948/api/shuffleServer/confOps/tempUpdate`

Is this ok? @jerqi

**Comment by jerqi** [comment]
> `curl -X POST http://localhost:19948/api/shuffleServer/confOps/update ` -> `curl -X POST http://localhost:19948/api/shuffleServer/confOps/tempUpdate`
> 
> Is this ok? @jerqi



> `curl -X POST http://localhost:19948/api/shuffleServer/confOps/update ` -> `curl -X POST http://localhost:19948/api/shuffleServer/confOps/tempUpdate`
> 
> Is this ok? @jerqi
http://localhost:19948/api/shuffleServer/confops/temp/update may be better. URI is't case sentive. I prefer not using camel style in the URI.

**Comment by maobaolong** [comment]
@jerqi As this is a use case of rest api update, I start another PR to improve the `conf update` rest api.

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
https://github.com/apache/incubator-uniffle/pull/2235

**Comment by maobaolong** [comment]
@jerqi Thanks for your review on this PR, merge it

**Pull request merged**
