### PR TITLE
[#1447] feat(client): Introduce configurations to control default behavior of RPC client

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Introduce two configurations to control the default behavior of the RPC client:
|Property Name|Default| Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|---|---|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|<client_type>.rss.client.rpc.timeout.ms|60000| Timeout in milliseconds for RPC calls.|
|<client_type>.rss.client.rpc.maxAttempts|3| When we fail to send RPC calls, we will retry for maxAttempts times.|

### Why are the changes needed?

For [#1447](https://github.com/apache/incubator-uniffle/issues/1447)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL @jerqi @zuston

**Review by jerqi — APPROVED** [review]
LGTM. Thanks @rickyma

**Review by zuston — COMMENTED** [review]
LGTM. But please fix the test failure.

**Review by jerqi — APPROVED** [review]

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
Merged. Thanks @rickyma

**Pull request merged**
