### PR TITLE
[#1731] improvement(server): Bump gRPC from 1.63.0 to 1.64.0

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Bump gRPC from 1.63.0 to 1.64.0.

### Why are the changes needed?

Fix: https://github.com/apache/incubator-uniffle/issues/1731.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by rickyma** [comment]
@zuston @jerqi PTAL

**Comment by jerqi** [comment]
Maybe we should upgrade to 1.63.1.

**Comment by rickyma** [comment]
[1.64.0](https://github.com/grpc/grpc-java/releases/tag/v1.64.0) includes a lot bug fixes. I've tested it. I think it will work well. WDTY?

**Comment by jerqi** [comment]
> [1.64.0](https://github.com/grpc/grpc-java/releases/tag/v1.64.0) includes a lot bug fixes. I've tested it. I think it will work well. WDTY?

OK. Maybe this is a fix and should be committed to branch 0.9.

**Comment by rickyma** [comment]
If you've already committed https://github.com/apache/incubator-uniffle/pull/1702 and https://github.com/apache/incubator-uniffle/pull/1704 to 0.9, then maybe you need to commit this as well.

**Review by zuston — APPROVED** [review]

**Comment by rickyma** [comment]
We can merge this.

**Pull request merged**
