### PR TITLE
[#2030] fix(client-spark): Remove javax and logging from relocation list to solve NoClassDefFoundError

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Do not relocate javax to avoid NoClassDefFoundError issue.

### Why are the changes needed?

Fix: #2030

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Thanks for the verify check by @zhengchenyu . This is not reproduced on my env.

### CODE REVIEW

**Comment by zuston** [comment]
Could you help review this? @zhengchenyu

**Comment by maobaolong** [comment]
@jerqi Please help to review this PR, thanks!

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi thanks for your review

**Pull request merged**
