### PR TITLE
[MINOR] fix(dashboard): Correct RegistrationTime to HeartbeatTime

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

The `RegistrationTime` in the dashboard shuffle-server page can make us confuse, I think it could be better to be  `HeartbeatTime`.

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Make the displayed title more meaningful.

### Does this PR introduce _any_ user-facing change?

(Please list the user-facing changes introduced by your change, including
  1. Change in user-facing APIs.
  2. Addition or removal of property keys.)

WebUI of dashboard

### How was this patch tested?

image

### CODE REVIEW

**Comment by zhengchenyu** [comment]
The metrics is from 'http://xx:xx/api/server/nodes', should be from ServerNode::timestamp, this is from heartbeat.
I think HeartbeatTime is more accurate.
LGTM+1

**Review by zuston — APPROVED** [review]
LGTM. Thanks for your contribution! @maobaolong and thanks @zhengchenyu for your review. 
Merged.

**Comment by rickyma** [comment]
After this PR, I think I can close https://github.com/apache/incubator-uniffle/issues/1471. Maybe we don't need registrationTime at all?

**Comment by maobaolong** [comment]
@rickyma It could be better to have registrationTime also, so we can create another ticket to record and display registrationTime?

**Comment by rickyma** [comment]
That would be great! Please go ahead if you have time. @maobaolong

**Pull request merged**
