### PR TITLE
[Feature] Introduce graceful decommission for shuffle server

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
[Feature] Introduce graceful decommission for shuffle server

### Why are the changes needed?
When shuffle servers needed to decommission are included in exclude-node-files, we hope it will exit when all apps finished.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Need. And it will added later.

### CODE REVIEW

**Comment by xianjingfeng** [comment]
I think decommission without restart coordinator or restart  shuffle server is better, We have another solution and i will create a pr tomorrow

**Comment by zuston** [comment]
I can’t got your thought fully. As i know, when need to make one shuffle server decommission, just add it to the exclude file in coordinator side. There is no need to restart coordinator/shuffle servers.

This PR is just to make shuffle server process exit once all apps finished.

**Comment by xianjingfeng** [comment]
> I can’t got your thought fully. As i know, when need to make one shuffle server decommission, just add it to the exclude file in coordinator side. There is no need to restart coordinator/shuffle servers.
> 
> This PR is just to make shuffle server process exit once all apps finished.

Sorry, i don't know `excludeNodes` update periodically before.
But if we have multi coordinator, we will change exclude-node-files multi times, and if we need to start shuffle server again, we need change them again. 
And  i think _**exclude**_ is not equal to _**decommission**_

**Comment by zuston** [comment]
> But if we have multi coordinator, we will change exclude-node-files multi times, and if we need to start shuffle server again, we need change them again.

Exclude-nodes-file could be stored in HDFS, so it dont need to sync multiple coordinators.

> And i think exclude is not equal to decommission
I think exclude-nodes-file could be as decommission for a shuffle server. But it should support two ways of decommission
1. Normal decommission. This will make coordinator wont do assignment for this node and let it shutdown quickly.
2. Graceful decommission. This will make coordinator wont do assignment for this node and let it graceful shutdown until all apps finished.

Please let me know what u think. @xianjingfeng

**Comment by zuston** [comment]
What do you have any ideas on this PR ? @jerqi

**Comment by jerqi** [comment]
> What do you have any ideas on this PR ? @jerqi

We need more discussion in issue #80 first.

**Pull request closed without merging**
