### PR TITLE
[ISSUE-106][IMPROVEMENT] Set rpc timeout for all rpc interface

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?
Solve issue #106 Set rpc timeout for all rpc interface

### Why are the changes needed?
If oom encountered in shuffle server, rpc client will blocked until shuffle server was killed

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need

### CODE REVIEW

**Comment by xianjingfeng** [comment]
It seems that ut fail becuase `rss.server.app.expired.withoutHeartbeat` was set too small

**Comment by xianjingfeng** [comment]
Should we modify the value of  `rss.server.app.expired.withoutHeartbeat` in all ut? @jerqi

**Comment by jerqi** [comment]
> Should we modify the value of `rss.server.app.expired.withoutHeartbeat` in all ut? @jerqi

Could you just modify the rpc timeout configuration to solve this problem?

**Comment by xianjingfeng** [comment]
> > Should we modify the value of `rss.server.app.expired.withoutHeartbeat` in all ut? @jerqi
> 
> Could you just modify the rpc timeout configuration to solve this problem?

This ut not fail every time, it is affected by host load. Maybe it will be normal to run again

**Comment by jerqi** [comment]
> > > Should we modify the value of `rss.server.app.expired.withoutHeartbeat` in all ut? @jerqi
> > 
> > 
> > Could you just modify the rpc timeout configuration to solve this problem?
> 
> This ut not fail every time, it is affected by host load. Maybe it will be normal to run again

 You can trigger the test when you close the pr and reopen the pr again. According to my experience, the test won't be flaky test, if there are multiple failure pipelines.

**Comment by jerqi** [comment]
cc @colinmjj

**Comment by xianjingfeng** [comment]
`Error:  writeTest  Time elapsed: 51.138 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected flush process
	at org.apache.uniffle.server.ShuffleFlushManagerTest.waitForFlush(ShuffleFlushManagerTest.java:315)
	at org.apache.uniffle.server.ShuffleFlushManagerTest.writeTest(ShuffleFlushManagerTest.java:123)`
Maybe something's wrong with CI ? @jerqi

**Comment by jerqi** [comment]
> `Error: writeTest Time elapsed: 51.138 s <<< FAILURE! org.opentest4j.AssertionFailedError: Unexpected flush process at org.apache.uniffle.server.ShuffleFlushManagerTest.waitForFlush(ShuffleFlushManagerTest.java:315) at org.apache.uniffle.server.ShuffleFlushManagerTest.writeTest(ShuffleFlushManagerTest.java:123)` Maybe something's wrong with CI ? @jerqi

It's a flaky test. If you rerun, it will succeed.

**Comment by jerqi** [comment]
If you want to see the log, you can download https://github.com/apache/incubator-uniffle/actions/runs/2779258464 
企业微信截图_ddffa6a0-c008-4150-bfa7-3fa21a08d420

**Comment by xianjingfeng** [comment]
I can't see the contents like this. I just can see simple maven log.

**Comment by jerqi** [comment]
> I can't see the contents like this. I just can see simple maven log.

Click the link that I give you, and search `Artifacts`

**Comment by xianjingfeng** [comment]
> Artifacts

I found it, thanks

**Comment by jerqi** [comment]
LGTM @colinmjj Do you have any other suggestion?

**Comment by colinmjj** [comment]
+1, LGTM

**Review by jerqi — APPROVED** [review]
Thanks for your contribution @xianjingfeng

**Pull request merged**
