### PR TITLE
[ISSUE-48][FEATURE] Init Operator Directory

### PR DESCRIPTION
**Pull request by wangao1236**
### What changes were proposed in this pull request?
for issue #48 
I init the operator first, and I will submit a following pr of crd. 

### Why are the changes needed?
Support to deploy Uniffle on K8S

### Does this PR introduce _any_ user-facing change?
We will write the docs later.

### How was this patch tested?
No need

### CODE REVIEW

**Comment by jerqi** [comment]
cc @zuston @czy006, could you help me review this patch?

**Comment by thousandhu** [comment]
thanks @wangao1236, i'm very interested in this issue and also hope to do sth. for help.

**Comment by wangao1236** [comment]
@thousandhu @jerqi

**Comment by wangao1236** [comment]
cc @thousandhu @jerqi

**Comment by jerqi** [comment]
LGTM, wait for others' suggestion.

**Comment by thousandhu** [comment]
+1, LGTM

**Comment by zuston** [comment]
LGTM +1. Thanks for your work @wangao1236

**Comment by czy006** [comment]
LGTM +1.

**Review by jerqi — APPROVED** [review]

**Comment by jerqi** [comment]
Merged, Thanks @wangao1236 @thousandhu @zuston @czy006

**Pull request merged**
