### PR TITLE
[MINOR] chore:correct the format of go files

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Correct the format fo go files.

### Why are the changes needed?

`build-operator.sh` cannot be executed normally.

build logs as follow:
```
image version release.0.4.0.453.g567872b8.dirty is dirty, dirty files:
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
No need.

### CODE REVIEW

**Comment by xianjingfeng** [comment]
Should we cover this case in workflow? @kaijchen

**Comment by kaijchen** [comment]
>  Should we cover this case in workflow? @kaijchen

Yes, we can add a format check in the build script.

**Comment by kaijchen** [comment]
seems golang is already checking the format, and the build failed in CI

**Comment by xianjingfeng** [comment]
> seems golang is already checking the format, and the build failed in CI

I found in my development environment, `go fmt`  will replace space with tab. Can this be configured?

**Comment by xianjingfeng** [comment]
It seems ok in current code base. Let me create an issue to discuss it.

**Pull request closed without merging**
