### PR TITLE
[Improvement] Use OR operation instead of serialization for cloning BitMaps

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes were proposed in this pull request?

1. Add `RssUtils#cloneBitMap()`.
2. Replace `deserializeBitMap(serializeBitMap(bitmap))` by `cloneBitMap(bitmap)`.

### Why are the changes needed?

1. No need to handle `IOException`.
2. More efficient.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

New unit test `RssUtilsTest#testCloneBitmap()`

### CODE REVIEW

**Comment by jerqi** [comment]
Could we have a simple benchmark test?

**Comment by kaijchen** [comment]
> Could we have a simple benchmark test?

Performance is not the main concern here.
Exception-free is more important.

**Comment by jerqi** [comment]
> > Could we have a simple benchmark test?
> 
> Performance is not the main concern here. Exception-free is more important.
> 
> If you find this change is impacting performance later, you can change the method body to
> 
> ```java
> try {
>     return deserializeBitMap(serializeBitMap(bitmap));
> } catch(IOException e) {
>     // not expected
> }
> ```
> 
> Just look at the body of `serializeBitMap` and `deserializeBitMap`, it feels they are more costly and error-prone.
> 
> And explicitly throwing RuntimeException is not a good practice, because they are difficult to catch (without catching real RuntimeException).

Sadly, we care the performance here. We need performance test to ensure that the pr won't bring worse performance. Bitmap method `or` will do many operations, it may cost much time,  I can't ensure the performance easily.

**Comment by kaijchen** [comment]
I'll include this test in this PR.

screenshot_c1ceb13e-0655-460a-a50f-552c793b057f

**Comment by kaijchen** [comment]
The leap is even bigger for large BitMap.

screenshot_ccc1ad40-80da-418d-9d17-568a6dc428c9

**Comment by jerqi** [comment]
Great work!

**Comment by jerqi** [comment]
Could you use some random number to test them again? Because bitmap will compress the ordered number, the size of bitmap will be smaller,  we test in more situations, the result will be more persuasive.

**Comment by kaijchen** [comment]
Random ints
image

Random longs
image

**Comment by kaijchen** [comment]
> I'll include the following test in this PR.

Removed this test because it might be flaky due to resource sharing in the CI environment.

**Review by jerqi — APPROVED** [review]
LGTM, thanks for your contribution @kaijchen.

**Comment by kaijchen** [comment]
Thanks @jerqi for the review.

**Pull request merged**
