### PR TITLE
[#1805][part-1] build: Support Scala 2.13

### PR DESCRIPTION
**Pull request by EnricoMi**
### What changes were proposed in this pull request?

Support compiling Spark client against Scala 2.13 dependencies.

### Why are the changes needed?

Starting with Spark 4, Scala 2.13 is required.

Fix: #1805

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI

### CODE REVIEW

**Comment by jerqi** [comment]
I don't prefer adding Scala 2.13. It will be complex to publish multiple Scala packages. We don't use many Scala code. It's better to use reflection to solve this kind of the issue.

**Comment by EnricoMi** [comment]
I think there is no need to publish multiple Scala  packages, only one Scala version per Spark version (as is). Users might still want to be able to compile their Spark client with the Scala version they use in their deployed Spark.

**Comment by jerqi** [comment]
It seems that we don't need to compile the package. The Scala 2.13 is only used for tests. It's ok if we don't depend on it for our source code.

**Review by jerqi — APPROVED** [review]
LGTM.

**Pull request merged**
