### PR TITLE
[ISSUE-283][FEATURE] Support snappy compression/decompression

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

This PR adds the support of snappy compression/decompression based on the example of https://github.com/apache/incubator-uniffle/pull/254. 

### Why are the changes needed?

Add a new feature.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT

### CODE REVIEW

**Comment by jerqi** [comment]
Should we modify the document about `rss.client.io.compression.codec` in  the https://github.com/apache/incubator-uniffle/blob/master/docs/client_guide.md?

**Comment by amaliujia** [comment]
@jerqi Yes! I updated that config's description accordingly.

**Comment by amaliujia** [comment]
The failing test seems to be flaky. What is the way to re-trigger the test?

**Comment by jerqi** [comment]
> The failing test seems to be flaky. What is the way to re-trigger the test?

I have re-triggered the test. It passed. You can close and reopen the pr to re-trigger the all the tests. It seems that only committers can re-trigger the single test.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @amaliujia

**Pull request merged**
