### PR TITLE
[#2203] feat(server) Add write file quantity info for application. 

### PR DESCRIPTION
**Pull request by lwllvyb**
### What changes were proposed in this pull request?

Add write file quantity info for application. 

### Why are the changes needed?

Fix: #2203 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
Locally

### CODE REVIEW

**Comment by lwllvyb** [comment]
**This PR is derived from another PR #2063 . I split the PR #2063 into several smaller PRs that are easier to review, and this one of them.**

**Comment by lwllvyb** [comment]
Ping @zuston

**Comment by lwllvyb** [comment]
Ping @zuston @jerqi @maobaolong @zhengchenyu 
Thanks again.

**Review by maobaolong — APPROVED** [review]
Sorry for the late review, It LGTM, thanks for your insight related contribution!

**Review by jerqi — APPROVED** [review]
LGTM.

**Pull request merged**
