### PR TITLE
[#2229] feat(server,client): Introduce `OutputUtils` class to reduce log size

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Introduce OutputUtils class to reduce log size

### Why are the changes needed?

Fix: #2229

### Does this PR introduce _any_ user-facing change?

Log become useful but tiny enough.

### How was this patch tested?

new UT

### CODE REVIEW

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi Thanks for your review, merge it

**Comment by zuston** [comment]
If having multi modules associated change, the style commit log could be unified as the `feat(server)(client)`. I have seen a lot of different styles like `feat(server,client)` and `feat(server/client)` . @maobaolong

**Comment by maobaolong** [comment]
@maobaolong Sorry for this mistake, will check it before merge.

**Comment by jerqi** [comment]
> If having multi modules associated change, the style commit log could be unified as the `feat(server)(client)`. I have seen a lot of illegal different styles like `feat(server,client)` and `feat(server/client)` . @maobaolong

A lot of projects adopt the style `feat(server,client)`, too.

**Pull request merged**
