### PR TITLE
[MINOR] feat(operator): Add support to pass annotations to coordinator nodeport/headless service

### PR DESCRIPTION
**Pull request by shlomitubul**
### What changes were proposed in this pull request?

Add support to pass a list of annotations per coordinator service (node port/headless).  

### Why are the changes needed?
Some tools use service annotations to create DNS records and currently is not supported.

### Does this PR introduce _any_ user-facing change?
Introduce 2 new optional fields in CRD: 
1. headlessServiceAnnotations
2. nodePortServiceAnnotations

### How was this patch tested?
UT + manually

### CODE REVIEW

**Comment by jerqi** [comment]
Could you add a UT in `coordinator_test.go`?

**Comment by shlomitubul** [comment]
> Could you add a UT in `coordinator_test.go`?

done

**Comment by jerqi** [comment]
Could you fix the UT?

**Comment by shlomitubul** [comment]
> Could you fix the UT?

UT seems to have passed. Build failure might be related to uncommitted auto-generated files, so I added those files (I didn't understand why they were needed in the first place since they were created in part of the CI build anyway?).

**Comment by jerqi** [comment]
> > Could you fix the UT?
> 
> UT seems to pass. Build failure might be related to uncommitted auto-generated files, so I added those files (I didn't understand why they were needed in the first place since they were created in part of the CI build anyway?).

Thanks for your contribution.  The build script will format the code and check whether there exists  code not committed.

**Pull request merged**
