### PR TITLE
[#611] chore: update project version to 0.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Update version to 0.8.0-SNAPSHOT

### Why are the changes needed?
For next release

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Don't need

### CODE REVIEW

**Comment by zuston** [comment]
I have create a new branch of `branch-0.7.0`, so let update the master version.

**Comment by kaijchen** [comment]
Can we call it `0.8.0-SNAPSHOT`?
Also, should we bump the version now or when 0.7.0 is released?

**Comment by kaijchen** [comment]
> I have create a new branch of `branch-0.7.0`, so let update the master version.

The new branch is `branch-0.7`, not `branch-0.7.0`. Because there might be `0.7.1` later.

**Comment by zuston** [comment]
> Can we call it 0.8.0-SNAPSHOT?

Yes, it looks better. 

> Also, should we bump the version now or when 0.7.0 is released?

I prefer now. Maybe the release process is long, we don't hope it blocks the PR merging.

> > I have create a new branch of `branch-0.7.0`, so let update the master version.
> 
> The new branch is `branch-0.7`, not `branch-0.7.0`. Because there might be `0.7.1` later.

Got it. Let me re-create.

**Comment by zuston** [comment]
And the CI failed in https://github.com/apache/incubator-uniffle/commit/7f9b5615162bd013426ab6d58f5054fa1cf68d0c. Do I need to fix this before this PR is merged

**Comment by kaijchen** [comment]
> And the CI failed in 7f9b561. Do I need to fix this before this PR is merged

It's OK, as long as CI in this PR passes. We can always backport fixes to release branches.

**Review by kaijchen — APPROVED** [review]
LGTM, thanks @zuston.

**Comment by kaijchen** [comment]
Thanks @zuston for hosting 0.7.0 release, and thanks @advancedxy for the review.

**Pull request merged**
