### PR TITLE
[#333] feat: expose metrics of TOP10 app bytes in one shuffle server

### PR DESCRIPTION
**Pull request by amaliujia**

### CODE REVIEW

**Comment by zuston** [comment]
The modification direction looks good to me. 

But the metrics looks incomplete. I think we should add the metrics, including the whole storage(memory&localfile&hdfs) occupied ratio and bytes for top10 single app, instead of only memory. But should we need the original metric output style, I have not a good idea yet. The original metric output style looks inproper for this scenario.

```yaml
// original metric output style
{
"metrics": [
{
"name": "xxx",
"labelNames": [],
"labelValues": [],
"value": 41332,
"timestampMs": null
}
]
}
```

And the top10 sorting, I think It only should be triggered by the scheduler thread to update, instead of updating every time on `updateCachedBlockIds`. Maybe this will cause performance regression.

Do you have other ideas on this? @jerqi @kaijchen .

**Comment by jerqi** [comment]
> The modification direction looks good to me.
> 
> But the metrics looks incomplete. I think we should add the metrics, including the whole storage(memory&localfile&hdfs) occupied ratio and bytes for top10 single app, instead of only memory. But should we need the original metric output style, I have not a good idea yet. The original metric output style looks inproper for this scenario.
> 
> ```yaml
> // original metric output style
> {
> "metrics": [
> {
> "name": "xxx",
> "labelNames": [],
> "labelValues": [],
> "value": 41332,
> "timestampMs": null
> }
> ]
> }
> ```
> 
> And the top10 sorting, I think It only should be triggered by the scheduler thread to update, instead of updating every time on `updateCachedBlockIds`. Maybe this will cause performance regression.
> 
> Do you have other ideas on this? @jerqi @kaijchen .

I think application level memory size is enough. Because the pressure mainly come from the memory which need to be flushed instead of data size of LOCALFILE or HDFS.

**Comment by zuston** [comment]
> I think application level memory size is enough. Because the pressure mainly come from the memory which need to be flushed instead of data size of LOCALFILE or HDFS.

Sometimes we want to find the app of max disk occupation, although it could be found by the command of `du`.  If having this metric, we could find the unreasonable app through the alert with the metric

**Comment by jerqi** [comment]
> > I think application level memory size is enough. Because the pressure mainly come from the memory which need to be flushed instead of data size of LOCALFILE or HDFS.
> 
> Sometimes we want to find the app of max disk occupation, although it could be found by the command of `du`. If having this metric, we could find the unreasonable app through the alert with the metric

Ok.

**Comment by zuston** [comment]
> That's another question. We needn't solve style problem in this pr.

Do you mean we should limit the change of this PR  only to support the bytes collection of single app? But if not exposing the metric, how to collect by external collector?

**Comment by jerqi** [comment]
> > That's another question. We needn't solve style problem in this pr.
> 
> Do you mean we should limit the change of this PR only to support the bytes collection of single app? But if not exposing the metric, how to collect by external collector?
> 
> Or do you mean the exposing metrics style could be implemented by another PR? ~

I  can't get your point. Why do we need care metrics output style?

**Pull request closed without merging**
