### PR TITLE
[ISSUE-290] Make RpcNodePort and HttpNodePort optional

### PR DESCRIPTION
**Pull request by amaliujia**
### What changes were proposed in this pull request?

This PR makes `RPC_SERVER_PORT` and `JETTY_HTTP_PORT` in RSS conf as optional by setting up default values into the config entries. 

### Why are the changes needed?

Feature.

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

UT

### CODE REVIEW

**Comment by amaliujia** [comment]
The `design.md` in fact mentions two values for each port config entry:

```
    # RpcNodePort represents the port required by the rpc protocol of the coordinators,
    # and the range is the same as the port range of the NodePort type service in kubernetes.
    # By default, we will deploy two coordinators to ensure active-active.
    rpcNodePort:
      - 30001
      - 30011
    # httpNodePort represents the port required by the http protocol of the coordinators,
    # and the range is the same as the port range of the NodePort type service in kubernetes.
    # By default, we will deploy two coordinators to ensure active-active.
    httpNodePort:
      - 30002
      - 30012
  ```
  
  However I didn't see two usages in the codebase. Maybe I have missed something?

**Review by zuston — APPROVED** [review]

**Comment by jerqi** [comment]
We only provide the default value in the configuration. https://github.com/apache/incubator-uniffle/blob/master/conf/server.conf and https://github.com/apache/incubator-uniffle/blob/master/conf/coordinator.conf
```
rss.rpc.server.port 19999
rss.jetty.http.port 19998
```
`design.md` is only the Kubernetes Operator design document.

**Comment by amaliujia** [comment]
I see it better now. Made a change to have the default value in config entries match the values in the provided config file.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @amaliujia @zuston

**Comment by jerqi** [comment]
Do you want to join our `Wechat` group? You can scan the QR code
企业微信截图_eb8711db-34bf-4365-bdab-15ef2e3ea119

**Pull request merged**
