### PR TITLE
[#796][0.7] bug: Fix the issues of MetricReporter

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

1. Support custom config keys defined in plugins
2. Refactor the logic for load config file
3. Fix some issues of metricReporter.

### Why are the changes needed?

Metric reporter is unusable.
Fix: #796 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
UT and Manual testing

### CODE REVIEW

**Comment by xianjingfeng** [comment]
It seems that this PR is merged to master in CI enviroment. But the first time is ok.
https://github.com/apache/incubator-uniffle/actions/runs/4684746312/jobs/8301194063

Do you know why? @kaijchen @jerqi

**Comment by jerqi** [comment]
> It seems that this PR is merged to master in CI enviroment. But the first time is ok. https://github.com/apache/incubator-uniffle/actions/runs/4684746312/jobs/8301194063
> 
> Do you know why? @kaijchen @jerqi

I cherry-pick a wrong commit. I have reverted it. it's strange that it influence your pr. You could rerun your pr.

**Comment by kaijchen** [comment]
> You could rerun your pr.

Please rebase or merge branch-0.7.

**Comment by jerqi** [comment]
> > You could rerun your pr.
> 
> Please rebase or merge branch-0.7.
企业微信截图_90010f5d-d8b3-4afd-9ad7-45b8ba63e889

But his commit history don't have my mistake commit. It's strange. But the error seems that it caused by my mistake commit.

**Comment by xianjingfeng** [comment]
It is ok now, just reopen it.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @xianjingfeng

**Pull request merged**
