### PR TITLE
[#1456] improvement(client): Better exception handling when calling requireBuffer using GRPC

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?
1、Refactor the method `ShuffleServerGrpcClient.requirePreAllocation`, calling `getBlockingStub().requireBuffer` only once.
2、Try-catch `getBlockingStub().requireBuffer`'s exception, log the error, and return `FAILED_REQUIRE_ID`.
3、Refactor the log to make it more appropriate.

### Why are the changes needed?

For [#1456](https://github.com/apache/incubator-uniffle/issues/1456)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL @jerqi @zuston

**Comment by rickyma** [comment]
It seems some tests failed. I don't know why the code below returns `INTERNAL_ERROR`. Can I get any detailed log messages responded by server?
```
RssSendShuffleDataResponse response =
        shuffleServerClient.sendShuffleData(sendShuffleDataRequest);
    assertSame(StatusCode.SUCCESS, response.getStatusCode());
```
@jerqi @zuston

**Comment by rickyma** [comment]
PTAL. @xianjingfeng

**Review by xianjingfeng — APPROVED** [review]
LGTM

**Pull request merged**
