### PR TITLE
Fix dashboard possible NPE

### PR DESCRIPTION
**Pull request by kuszz**
### Why are the changes needed?

Can't remove lost server on dashboard  

Fix: #1954 

### Does this PR introduce _any_ user-facing change?

No.

### CODE REVIEW

**Comment by kuszz** [comment]
@yl09099 could you review this pr?

**Comment by maobaolong** [comment]
@kuszz You can format this title to looks like others

**Comment by yl09099** [comment]
> @yl09099 could you review this pr?

I changed it in #1965, thanks

**Comment by kuszz** [comment]
> > @yl09099 could you review this pr?
> 
> I changed it in #1965, thanks

@yl09099 ok, thank you

**Pull request closed without merging**
