### PR TITLE
[#854][FOLLOWUP] feat(tez): Add RssShuffle to handle event and generate fetch task

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

add RssShuffle to handle event and generate fetch task

### Why are the changes needed?

Fix:  https://github.com/apache/incubator-uniffle/issues/854

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

unit test, we will push test case in this PR

### CODE REVIEW

**Comment by lifeSo** [comment]
test case was added.

**Comment by jerqi** [comment]
企业微信截图_f7698dd0-b331-4801-b34e-2543324d067e

**Comment by lifeSo** [comment]
> 企业微信截图_f7698dd0-b331-4801-b34e-2543324d067e

let me push other code

**Comment by lifeSo** [comment]
> 企业微信截图_f7698dd0-b331-4801-b34e-2543324d067e

RssShuffle file was pushed in this PR, we could merge that RssShuffle file first then merge this file.

https://github.com/apache/incubator-uniffle/pull/948/files

**Comment by lifeSo** [comment]
I merged and pushed RssShuffleScheduler.java

**Comment by lifeSo** [comment]
> I merged and pushed RssShuffleScheduler.java


I merged and pushed RssShuffleScheduler.java

**Comment by lifeSo** [comment]
Dalao please see see, all file compile is ok.

**Review by jerqi — APPROVED** [review]
LGTM, merged. thanks

**Pull request merged**
