### PR TITLE
[#2044] improvement: Remove console from log4j2.xml.

### PR DESCRIPTION
**Pull request by zhengchenyu**
### What changes were proposed in this pull request?

remove console from log4j2.xml

### Why are the changes needed?

Fix: #2044

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

test in physical machine

### CODE REVIEW

**Comment by zhengchenyu** [comment]
log4j2.xml in unit test is not changed. I think this provides a more debugging approach.

**Review by maobaolong — APPROVED** [review]
Discussed offline, This change LGTM. @zhengchenyu Thansk for your contribiton!

**Review by zuston — APPROVED** [review]
lgtm.

**Comment by zuston** [comment]
Thanks @zhengchenyu @maobaolong

**Pull request merged**
