### PR TITLE
[#881] fix: Ensure LocalStorageMeta disk size is correctly updated when events are processed

### PR DESCRIPTION
**Pull request by awdavidson**
### What changes were proposed in this pull request?
Ensure all events are marked as understorage, this will result to the LocalStorageMeta being updated when events are processed.

### Why are the changes needed?
Currently LocalStorageMeta is only update with metrics from the first event in a given shuffleId and partitionId, the first event updates metrics because there is no entry in `partitionsOfStorage` and the event get marked as `underStorage`, however, for future events in the same shuffleId and partitionId `selectStorage` returns the storage and does not mark the event as `underStorage` so when `updateWriteMetrics` is called, `event.getUnderStorage()` returns null and `storage.updateWriteMetrics(metrics);` is skipped.

As metrics are not updated correctly, `LocalStorage.canWrite` will not return the correct result.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?
Added unit test which covers multi events for the same shuffleId and partitionId

### CODE REVIEW

**Comment by jerqi** [comment]
@zuston Could you review this pr? Because you are more familiar with this part of code.

**Comment by zuston** [comment]
> @zuston Could you review this pr? Because you are more familiar with this part of code.

Oh, yes, let me take a look in the next few days

**Comment by connorlwilkes** [comment]
I noticed this whilst benchmarking Uniffle. It makes the settings related to disk capacity almost void

**Review by jerqi — APPROVED** [review]
LGTM, I think we can merge this pr first. @zuston When you have time, you can give another suggestion and raise a follow-up pr. Thanks all.

**Comment by jerqi** [comment]
@awdavidson Could you tell me your company? Do you use Uniffle in your production environment?

**Comment by jerqi** [comment]
@awdavidson There is conflict in the branch 0.7. Could you raise a pr for branch 0.7?

**Pull request merged**
