### PR TITLE
[#483] fix: use the correct storage type to match with server's conf

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

(Please outline the changes and how this PR fixes the issue.)

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Fix: # (issue)

### Does this PR introduce _any_ user-facing change?

(Please list the user-facing changes introduced by your change, including
  1. Change in user-facing APIs.
  2. Addition or removal of property keys.)

No.

### How was this patch tested?

(Please test your changes, and provide instructions on how to test it:
  1. If you add a feature or fix a bug, add a test to cover your changes. 
  2. If you fix a flaky test, repeat it for many times to prove it works.)

### CODE REVIEW

**Comment by zuston** [comment]
Do you have any ideas on this? @jerqi. I don't find the root cause.

**Comment by jerqi** [comment]
Why do `ShuffleServerFaultToleranceTest` have `.CoordinatorAssignmentTest.testSilentPeriod`?
企业微信截图_3016679e-65a2-4c17-86be-89b47aece3ac

**Comment by jerqi** [comment]
cc @xianjingfeng Could you have a look?

**Comment by jerqi** [comment]
```
ShuffleServerGrpcClient for host[10.1.0.4], port[20002] due to io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at org.apache.uniffle.storage.handler.impl.MemoryClientReadHandler.readShuffleData(MemoryClientReadHandler.java:77)
	at 
```
Log shows that the server 2 isn't available.

**Comment by xianjingfeng** [comment]
> ```
> ShuffleServerGrpcClient for host[10.1.0.4], port[20002] due to io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
> 	at org.apache.uniffle.storage.handler.impl.MemoryClientReadHandler.readShuffleData(MemoryClientReadHandler.java:77)
> 	at 
> ```
> 
> Log shows that the server 2 isn't available.

I don't know why server 2 become unavailable. Should we catch `StatusRuntimeException` and retry?

**Comment by jerqi** [comment]
https://github.com/apache/incubator-uniffle/pull/705 Fixed.

**Pull request closed without merging**
