### PR TITLE
[MINOR][IMPROVEMENT] Return index-file size of n*SEGMENT_SIZE in HDFS reading

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?
Return index-file size of n*SEGMENT_SIZE in HDFS reading

### Why are the changes needed?
It should keep consistent with the logic of returning the complete index data in localfile reader that data size is always n*SEGMENT_SIZE.

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by zuston** [comment]
PTAL @jerqi

**Comment by zuston** [comment]
PTAL @jerqi . If OK, I will add some UTs.

**Comment by jerqi** [comment]
> PTAL @jerqi . If OK, I will add some UTs.

You can go ahead.

**Review by jerqi — APPROVED** [review]
LGTM, thanks @zuston

**Pull request merged**
