### PR TITLE
[#1728] feat(server): Introduce disks timeout metrics

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

Introduce disks timeout metrics.

### Why are the changes needed?

For https://github.com/apache/incubator-uniffle/issues/1728.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

### CODE REVIEW

**Comment by rickyma** [comment]
PTAL @zuston @jerqi

**Comment by rickyma** [comment]
The test pipeline did not work properly, the checks have been successful for a while now.
image

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by zuston — APPROVED** [review]
LGTM

**Pull request merged**
