### PR TITLE
[#2136][FOLLOWUP] improvement(server,coordinator): Modify the path of update conf rest api

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Modify the path of update conf rest api

### Why are the changes needed?

To make it clear to show this is a temp update, do not update the config file.

### Does this PR introduce _any_ user-facing change?

Path modified to

`http://localhost:19948/api/shuffleServer/confOps/update` ->
`http://localhost:19948/api/shuffleserver/conf/ops/temp/update`

### How was this patch tested?

Tested Locally.

```
➜  ~ curl -X POST http://localhost:19948/api/shuffleServer/conf/ops/temp/update \
-H "Content-Type: application/json" \
-d '{"update":{"rss.server.flush.localfile.threadPool.size": "122", "rss.server.flush.thread.alive": "112", "rss.rpc.executor.size": "123"}}'
temporarily effective until restart: Update successfully%
```

### CODE REVIEW

**Comment by jerqi** [comment]
> ### What changes were proposed in this pull request?
> Modify the path of update conf rest api
> 
> ### Why are the changes needed?
> To make it clear to show this is a temp update, do not update the config file.
> 
> ### Does this PR introduce _any_ user-facing change?
> Path modified to
> 
> `http://localhost:19948/api/shuffleServer/confOps/update` -> `http://localhost:19948/api/shuffleserver/confops/temp/update`
> 
> ### How was this patch tested?
> No

Maybe  `http://localhost:19948/api/shuffleserver/conf/ops/temp/update` may be better.

**Comment by maobaolong** [comment]
@jerqi Done, PTAL.

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi Thanks for your review. merge it.

**Pull request merged**
