### PR TITLE
[#854][FOLLOWUP] feat(tez): Add Rss Input Class to begin Tez input task

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

Add Rss Input Class to begin Tez input task

### Why are the changes needed?

Fix: https://github.com/apache/incubator-uniffle/issues/854

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

unit test

### CODE REVIEW

**Comment by lifeSo** [comment]
image

Tez original throw Exception, means should not run to here.

eg:
https://github.com/apache/tez/blob/7a56e9bd9de0764f69854ca4d35e054bef70cc38/tez-runtime-library/src/main/java/org/apache/tez/runtime/library/input/UnorderedKVInput.java#L175

**Comment by lifeSo** [comment]
DaLao please see one see, is there any problems ?

**Review by jerqi — APPROVED** [review]
LGTM, merged first.

**Comment by lifeSo** [comment]
> LGTM, merged first.

Thanks Dalao!

**Pull request merged**
