### PR TITLE
[#1324] fix(dashboard): fix dashboard data display bug.

### PR DESCRIPTION
**Pull request by qijiale76**
### What changes were proposed in this pull request?

fix dashboard data display bug.

### Why are the changes needed?

Fix: #1324

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested in our cluster.

### CODE REVIEW

**Comment by qijiale76** [comment]
@yl09099 Could you please review this PR?

**Comment by yl09099** [comment]
> @yl09099 Could you please review this PR?

Some problems I have changed in the next PR, please check them after I merge them.

**Comment by qijiale76** [comment]
> > @yl09099 Could you please review this PR?
> 
> Some problems I have changed in the next PR, please check them after I merge them.

OK. I didn't notice the relevant commit before submitting this PR. I will close this PR.

**Comment by yl09099** [comment]
> OK. I didn't notice the relevant commit before submitting this PR. I will close this PR.

I have looked at some things that can be changed. Wait for two days and help you review later.

**Comment by jerqi** [comment]
@yl09099 Do we need this pr yet?

**Comment by yl09099** [comment]
> @yl09099 Do we need this pr yet?

These issues are fixed and can be turned off directly.

**Pull request closed without merging**
