### PR TITLE
[MINOR] feat(coordinator/server): Support RPC from-address to audit log and refactor RpcAuditContext

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

- Support RPC from-address to audit log
- Do refactor to RpcAuditContext

### Why are the changes needed?

Add from information for each call to make it easy for trouble-shooting.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Start coordinator\servers and check the rpc auditlog

```
# coordinator_rpc_audit.log
[2024-08-05 19:12:19.532] cmd=registerApplicationInfo	statusCode=SUCCESS	from=/x.x.x.x:49416	executionTimeUs=1514	appId=app-20240805190949-0009_1722856187872	args{user=user}

# server_rpc_audit.log
[2024-08-05 19:12:21.511] cmd=requireBuffer	statusCode=SUCCESS	from=/x.x.x.x:43904	executionTimeUs=1294	appId=app-20240805190949-0009_1722856187872	shuffleId=0	args{requireSize=233, partitionIdsSize=1}

[2024-08-05 19:12:21.778] cmd=sendShuffleData	statusCode=SUCCESS	from=/x.x.x.x:39340	executionTimeUs=25464	appId=app-20240805190949-0009_1722856187872	shuffleId=0	args{requireBufferId=4, requireSize=233, isPreAllocated=true, requireBlocksSize=39, stageAttemptNumber=0}

```

### CODE REVIEW

**Comment by jerqi** [comment]
Do we have the document to use the audit log?

**Comment by maobaolong** [comment]
@jerqi We do not have the document related rpc audit log yet, I'd glad to add one to describe how to use `ShuffleServerRpcAuditLog`, `ShufleServerStorageAudtilog`, `CoordinatorRpcAuditlog`, may I add a documents PR after this PR, https://github.com/apache/incubator-uniffle/pull/2014, and https://github.com/apache/incubator-uniffle/pull/2007 ?

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
Rebased on tested.

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@zuston Would you like to take a look at this PR? Thanks.

**Comment by maobaolong** [comment]
@jerqi Thanks for your review!

**Pull request merged**
