### PR TITLE
[MINOR] improvement(mr): Add @Test to activate test case

### PR DESCRIPTION
**Pull request by lifeSo**
### What changes were proposed in this pull request?

Add @Test to activate test case

### Why are the changes needed?
Just for Add @Test to activate test case

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

unit test

### CODE REVIEW

**Review by jerqi — APPROVED** [review]
LGTM, wait for CI. thanks @lifeSo

**Comment by jerqi** [comment]
It seems unrelated to #854. We use minor  if this pr fix minor issue.

**Comment by lifeSo** [comment]
> It seems unrelated to #854. We use minor if this pr fix minor issue.

I think it does not matter whether it related or not.

**Comment by jerqi** [comment]
> > It seems unrelated to #854. We use minor if this pr fix minor issue.
> 
> I think it does not matter whether it related or not.

We should use correct titile.

**Pull request merged**
