### PR TITLE
[#2065] Fix QuorumTest to use random port

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

As title.

### Why are the changes needed?

Fix: #2065

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing UTs.

### CODE REVIEW

**Review by zuston — COMMENTED** [review]
If the #2068 is merged, does this need to change? @maobaolong

**Comment by maobaolong** [comment]
@zuston Thanks for you review, I think @2068 and this PR are two way to avoid port conflict.
- #2068 aimed to try to use an free port, but cannot promise to use the free port, since outer Process could obtain the same port too.
- This PR aimed to start `Process` with port `0` and export the listen port which `Coordinator` process is using now, and the other Uniffle process can get the `Coordinator` listening port and connect it with that port.

**Review by jerqi — APPROVED** [review]
LGTM.

**Comment by maobaolong** [comment]
@jerqi @zuston Thanks for your review

**Pull request merged**
