### PR TITLE
[#1182] fix(operator): The LeaderElectionNamespace of the rss-controller is hard-coded to kube-system.

### PR DESCRIPTION
**Pull request by qijiale76**
### What changes were proposed in this pull request?

(Please outline the changes and how this PR fixes the issue.)

get namespace from user configuration

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Fix: #1182 

### Does this PR introduce _any_ user-facing change?

(Please list the user-facing changes introduced by your change, including
  1. Change in user-facing APIs.
  2. Addition or removal of property keys.)

No.

### How was this patch tested?

(Please test your changes, and provide instructions on how to test it:
  1. If you add a feature or fix a bug, add a test to cover your changes. 
  2. If you fix a flaky test, repeat it for many times to prove it works.)

Tested in our cluster.

### CODE REVIEW

**Comment by jerqi** [comment]
Could you paste your screen shot of test result?

**Comment by qijiale76** [comment]
> Could you paste your screenshot of the test result?

Sure, We use namespace names `uniffle` and `uniffle2`.

**Before Applying the Patch:**

For the `uniffle` namespace:
```
leaderelection.go:278] successfully renewed lease kube-system/rss-controller-uniffle.apache.org
```

For the `uniffle2` namespace:

```
leaderelection.go:352] lock is held by rss-controller-64df7df9fd-k2g49_153e6f91-4d42-4bc5-b6c1-774467406a4e and has not yet expired
leaderelection.go:253] failed to acquire lease kube-system/rss-controller-uniffle.apache.org
```

**After Applying the Patch:**

```
leaderelection.go:278] successfully renewed lease uniffle/rss-controller-uniffle.apache.org
```
```
leaderelection.go:278] successfully renewed lease uniffle2/rss-controller-uniffle.apache.org
```

**Review by jerqi — APPROVED** [review]
LGTM, merged to master. Thanks @qijiale76

**Comment by qijiale76** [comment]
> LGTM, merged to master. Thanks @qijiale76

Thank you.

**Pull request merged**
