### PR TITLE
[#2003][FOLLOWUP] fix(client): Replace rss.rpc.client.type.grpc.timeout with rss.client.rpc.timeout.ms in RssShuffleManagerBase

### PR DESCRIPTION
**Pull request by xumanbu**
### What changes were proposed in this pull request?

1. Configure `rpcTimeout` in ShuffleManagerClient using `rss.client.rpc.timeout.ms`.  
2. Remove the `rss.rpc.client.type.grpc.timeout` configuration.

### Why are the changes needed?

Fix: #2003 

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
UT

### CODE REVIEW

**Review by rickyma — APPROVED** [review]
LGTM

**Comment by jerqi** [comment]
Do you need to modify the document, too?

**Comment by rickyma** [comment]
Is `ShuffleManageClient` the correct name of the file?

**Review by rickyma — APPROVED** [review]
LGTM

**Pull request merged**
