### PR TITLE
[#2282] improvement(spark3): Invoke with object self in DelegationRssShuffleManager

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

Fix the bug of none object self when invoking the reflection method.

### Why are the changes needed?

Fix: #2282

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by jerqi** [comment]
What will it happen if we don't have this?

**Comment by zuston** [comment]
> What will it happen if we don't have this?

Nothing will happen, because we bypass the getReader in the DelegationRssShuffleManager, so the acutall getReader invoking will happen in the underlying concrate shuffle manager. But this is an obvious bug, if someone wants to implement custom shuffle manager, he will follow the incorrect examples.

**Comment by jerqi** [comment]
> > What will it happen if we don't have this?
> 
> Nothing will happen, because we bypass the getReader in the DelegationRssShuffleManager, so the acutall getReader invoking will happen in the underlying concrate shuffle manager. But this is an obvious bug, if someone wants to implement custom shuffle manager, he will follow the incorrect examples.

So I think this is an improvement instead of a bug fix. If this is bug fix, we would better have a ut for it.

**Review by jerqi — APPROVED** [review]

**Review by maobaolong — APPROVED** [review]
@zuston Good catch! We encountered this issue too in this week! Thanks for your contribution!

**Comment by wForget** [comment]
> Nothing will happen, because we bypass the getReader in the DelegationRssShuffleManager, so the acutall getReader invoking will happen in the underlying concrate shuffle manager. But this is an obvious bug, if someone wants to implement custom shuffle manager, he will follow the incorrect examples.

I prefer to infer the appropriate shuffle manager from ShuffleHandle rather than overriding the shuffle manager configuration on the dirver side, so that we can implement stage-level fallback.

**Pull request merged**
