### PR TITLE
[#1894] fix(server): Fix NPE caused by app not found issue

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes were proposed in this pull request?

Fix the npe issue within shuffle server

### Why are the changes needed?

Fix: #1894

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested on our test cluster

### CODE REVIEW

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by rickyma — APPROVED** [review]
LGTM

**Comment by rickyma** [comment]
Merged to master. Thanks @maobaolong @jerqi

**Comment by maobaolong** [comment]
@jerqi @rickyma Thanks for your review!

**Pull request merged**
