### PR TITLE
[TYPO] Replace Chinese colon by ASCII colon

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes were proposed in this pull request?

Replace `：` by `: `.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No need.

### CODE REVIEW

**Comment by jerqi** [comment]
@zuston Kerberos test seems flaky.

**Comment by zuston** [comment]
> @zuston Kerberos test seems flaky.

Yes. This test makes me confused, I will take a look

**Review by zuston — APPROVED** [review]

**Comment by zuston** [comment]
Merged. Thanks @kaijchen

**Comment by kaijchen** [comment]
Thanks @zuston for merge this.

**Comment by jerryshao** [comment]
It would be better to cherry-pick this to 0.6 branch and kick off a new RC release. CC\ @jerqi

**Comment by jerqi** [comment]
> It would be better to cherry-pick this to 0.6 branch and kick off a new RC release. CC\ @jerqi

Ok, I will cherry-pick this pr.

**Pull request merged**
